Stopping application shows error #5830
LiskHQ/lisk-sdk pull request #5831
Opened 2020-09-22 09:36 UTC by ManuGowda

### What was the problem?

This PR resolves #5830 

### How was it solved?

- change the order of cleanup
- add missing await

### How was it tested?

- Updated unit test

2020-09-22 09:46 UTC, pablitovicente approved these changes

2020-09-22 09:49 UTC, pablitovicente commented on framework/src/node/node.ts
> +		await this._forgingJob.start();
This await might have been left out to avoid blocking here; maybe check with original author. Rest of PR looks good.

2020-09-22 11:37 UTC, pablitovicente requested changes
Still failing. So needs more research.

2020-09-22 17:26 UTC, shuse2 approved these changes

2020-09-22 17:28 UTC, shuse2 commented
Although this is not fixing the root problem, it is not affecting the application behavior so let's merge this PR but keep the issue open in the backlog

2020-09-23 08:03 UTC, pablitovicente approved these changes

2020-09-23 08:05 UTC, merged