5846 default app config
LiskHQ/lisk-sdk pull request #5889
Opened 2020-10-19 14:26 UTC by Incede

### What was the problem?

This PR resolves #5846 

### How was it solved?

* Initialize default config parameters in DPos & Token modules and in `application_config_schema.ts`

### How was it tested?

* Add unit test
* Test manually like `app = Application.defaultApplication(genesisBlock)` by linking to local `lisk-sdk/sdk`

2020-10-19 15:40 UTC, shuse2 requested changes

2020-10-19 15:40 UTC, shuse2 commented on framework/test/unit/application.spec.ts
> +			expect(app.config).toBeDefined();
i think it would be nice to check if the optional configs (like minRemainingBalance) is set

2020-10-19 15:40 UTC, shuse2 commented on framework/test/unit/application.spec.ts
> +		/*
we can delete the test if no longer valid, same for below

2020-10-19 15:40 UTC, shuse2 commented on framework/src/modules/token/token_module.ts
> +			: '5000000';
prefer to define constant

2020-10-20 13:50 UTC, shuse2 approved these changes

2020-10-20 14:35 UTC, mitsuaki-u approved these changes
LGTM

2020-10-20 15:16 UTC, merged