Create IPC Client for API - Closes #5923
LiskHQ/lisk-sdk pull request #5947
Opened 2020-11-04 16:11 UTC by mitsuaki-u

### What was the problem?

This PR resolves #5293 

### How was it solved?

- Create IPC client class
- Create util function to create IPC
- Create IPC server for integration test purposes
- Add integration tests

### How was it tested?

Run ipc integration test

2020-11-04 16:50 UTC, shuse2 requested changes

2020-11-04 16:50 UTC, shuse2 commented on elements/lisk-api-client/src/index.ts
> +export { IPCChannel } from './ipc_channel';
this should not be exposed

2020-11-04 16:50 UTC, shuse2 commented on elements/lisk-api-client/test/integration/ipc_channel.spec.ts
> +const socketsDir = pathResolve(`${homedir()}/.lisk/integration/ipc_client`);
variable should be in the `describe` block

2020-11-04 16:50 UTC, shuse2 commented on elements/lisk-api-client/src/create_api_client.ts
> +	const client = new APIClient(ipcChannel);
`client.init()` should be called here

2020-11-04 18:13 UTC, shuse2 approved these changes

2020-11-05 08:31 UTC, pablitovicente approved these changes

2020-11-05 08:38 UTC, merged