Update actions/events communication format to JSON-RPC - Closes #5918
LiskHQ/lisk-sdk pull request #5948
Opened 2020-11-04 17:27 UTC by ManuGowda

### What was the problem?

This PR resolves #5918

### How was it solved?

- Update action, events, bus, channels to
  - requests jsonrpc
  - respond jsonrpc
  - subscribe to events for jsonrpc notifications

### How was it tested?

2020-11-04 18:12 UTC, shuse2 commented on framework/src/controller/jsonrpc/index.ts
> + * Copyright © 2020 Lisk Foundation
this file should be called `types`?

2020-11-04 18:12 UTC, shuse2 commented on framework/src/controller/action.ts
> +		// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
why this is disabled?

2020-11-05 11:17 UTC, nazarhussain requested changes

2020-11-05 11:17 UTC, nazarhussain commented on framework/src/controller/action.ts
> +		method: string,
I don't think changing `name` to `method` or removing `module` attribute is appropriate here. In framework we still call and should call it `action name` and `action.module`. The change should be translated in `toJsonRPC` function where ``method: `${module}:${name}` ``

2020-11-05 11:17 UTC, nazarhussain commented on framework/src/controller/action.ts
> +		this.id = id;
This attribute seems required but not asserted neither any default value is assigned.

2020-11-05 11:17 UTC, nazarhussain commented on framework/src/controller/action.ts
> +		return eventName;
I don't see why these are required here. If its a needed, you can add those in initializer and assign to private variables.

2020-11-05 11:17 UTC, nazarhussain commented on framework/src/controller/action.ts
> +	public static fromJSONRPC(data: RequestObject | string): Action {
I would suggest for `fromJsonRPC`

2020-11-05 13:15 UTC, nazarhussain approved these changes

2020-11-05 13:22 UTC, shuse2 approved these changes

2020-11-05 13:36 UTC, merged