Update lisk-sdk README - Closes #6032
LiskHQ/lisk-sdk pull request #6033
Opened 2020-11-26 17:23 UTC by ManuGowda

### What was the problem?

This PR resolves #6032 

### How was it solved?

:nail_care: Update README.md

### How was it tested?
NA

2020-11-26 17:32 UTC, shuse2 requested changes

2020-11-26 17:32 UTC, shuse2 commented on framework-plugins/lisk-framework-forger-plugin/README.md
> +@liskhq/lisk-framework-forger-plugin is a plugin for lisk-framework that monitors configured delegates forging activity and voters information.
if we change here, package json also needs to be adjusted?

2020-11-26 17:32 UTC, shuse2 commented on framework-plugins/lisk-framework-monitor-plugin/README.md
> +	port: number,
i think we can keep it as optional as it has default?

2020-11-27 08:48 UTC, nazarhussain approved these changes

2020-11-27 09:01 UTC, shuse2 approved these changes

2020-11-27 09:11 UTC, merged