Respond status code when client IP not allowed - Closes #6037
LiskHQ/lisk-sdk pull request #6044
Opened 2020-12-09 14:17 UTC by Incede

### What was the problem?

This PR resolves #6037

### How was it solved?

* Handle error status response

### How was it tested?
```
lisk-core start --enable-http-api-plugin --http-api-plugin-port=5000 --http-api-plugin-whitelist=1.2.3.4
curl --verbose http://127.0.0.1:5000/api/node/info
```

2020-12-09 16:50 UTC, shuse2 requested changes
same change should be applied for monitor plugin

2020-12-09 16:50 UTC, shuse2 commented on framework-plugins/lisk-framework-http-api-plugin/src/middlewares/errors.ts
> +	const statusCode = (err as ErrorWithStatus).statusCode
maybe it's better to check like
```
const statusCode = err instanceof ErrorWithStatus ? err.statusCode : 500;
```

2020-12-10 08:46 UTC, nazarhussain requested changes

2020-12-10 08:46 UTC, nazarhussain commented on framework-plugins/lisk-framework-http-api-plugin/src/middlewares/errors.ts
> +export class ErrorWithStatus extends Error {
```suggestion
export class HTTPError extends Error {
```

2020-12-10 10:12 UTC, nazarhussain approved these changes

2020-12-10 11:30 UTC, shuse2 approved these changes

2020-12-10 12:34 UTC, merged