Enable child process IPC plugins - Closes #6010
LiskHQ/lisk-sdk pull request #6064
Opened 2021-01-06 14:40 UTC by mitsuaki-u

### What was the problem?

This PR resolves #6010 

### How was it solved?

Add checks in controller and bus for rpc / ipc configurations.

### How was it tested?

- Add unit tests
- Update functional tests

2021-01-08 14:22 UTC, shuse2 requested changes
LGTM except one comment =)

2021-01-08 14:22 UTC, shuse2 commented on framework/src/controller/bus.ts
> +		if (this.config.rpc.enable && this.config.rpc.mode === 'ipc') {
```suggestion
		if (this.config.rpc.enable) {
```

2021-01-11 08:55 UTC, nazarhussain approved these changes

2021-01-11 09:42 UTC, shuse2 approved these changes

2021-01-11 09:43 UTC, merged