Create network config bootstrapping command - Closes #6073
LiskHQ/lisk-sdk pull request #6080
Opened 2021-01-15 15:23 UTC by Incede

### What was the problem?

This PR resolves #6073 

### How was it solved?

* Create network config bootstrapping command

### How was it tested?

* Added unit tests
* Tested manually

2021-01-15 16:18 UTC, shuse2 requested changes

2021-01-15 16:18 UTC, shuse2 commented on commander/src/utils/config.ts
> +	networkVersion: '1.1',
i think default can be `1.0`

2021-01-15 16:18 UTC, shuse2 commented on commander/src/commands/generate/network-config.ts
> +				this.error('Aborting');
```suggestion
				this.error('Cancelled to overwrite the config.');
```

2021-01-15 16:18 UTC, shuse2 commented on commander/src/commands/generate/network-config.ts
> +					'A config file already exists at the given location. Do you want to overwrite it ?',
```suggestion
					'A config file already exists at the given location. Do you want to overwrite it?',
```

2021-01-15 16:43 UTC, Incede commented on commander/src/commands/generate/network-config.ts
> +		identifier: flagParser.string({
I think `community-identifier` is not allowed as a flag

2021-01-15 17:31 UTC, Incede commented on commander/src/commands/generate/network-config.ts
> +		'generate:network-config mydir --label alpha-sdk-app',
not sure what you mean here, can you please elaborate ?

2021-01-18 08:18 UTC, nazarhussain approved these changes

2021-01-18 10:14 UTC, shuse2 approved these changes

2021-01-18 10:15 UTC, merged