Create oclif commands skeleton in the template - Closes #6075
LiskHQ/lisk-sdk pull request #6085
Opened 2021-01-19 11:37 UTC by ManuGowda

### What was the problem?

This PR resolves #6075 

### How was it solved?

- Add base commands to commander
- Add commands to `lisk-ts` template

### How was it tested?

1. `cd lisk-sdk`; `yarn; yarn build`
2. `cd commander; yarn link`
3. `mkdir /tmp/test_lisk; cd /tmp/test_lisk`
4. `../lisk-sdk/commander/bin/run init`
5. `yarn link lisk-commander`
6. `./bin/run`

2021-01-19 17:24 UTC, shuse2 requested changes
generally LGTM

2021-01-19 17:24 UTC, shuse2 commented on commander/src/bootstrapping/templates/lisk-template-ts/templates/app/src/commands/account/show.ts
> +export { AccountShowCommand } from 'lisk-commander';
For all the commands, it should be either consistently expose as `default` or as object.
ie) some file exposes as `default class` but some as object

2021-01-19 17:24 UTC, shuse2 commented on commander/src/bootstrapping/templates/lisk-template-ts/templates/app/src/commands/start.ts
> +	static flags = {
Failing on build here

2021-01-20 11:07 UTC, nazarhussain requested changes
The `dataPath` logic in all the commands is not compatible with custom app. It always point to `~/.lisk/lisk-core` which is wrong in reference to custom app. Hence every command using `dataPath` in one or other way is failing.

2021-01-20 11:07 UTC, nazarhussain commented on commander/src/bootstrapping/commands/blockchain/hash.ts
> +		}),
There is a `data-path` in every other command. Would not it be nice to export such flags independently and reuse. Something like below. 

import commonFlags from '../common_flags`

```
static flags = {
     commonFlags.dataPath
}
```

2021-01-20 11:07 UTC, nazarhussain commented on commander/src/bootstrapping/commands/start.ts
> +		this.log(`Starting Lisk Core at ${getFullPath(dataPath)}.`);
```suggestion
		this.log(`Starting Lisk application at ${getFullPath(dataPath)}.`);
```

2021-01-21 11:38 UTC, ManuGowda commented
@nazarhussain i have created a separate issue to address the improvements https://github.com/LiskHQ/lisk-sdk/issues/6087

2021-01-21 12:38 UTC, shuse2 commented on commander/package.json
> +		"lisk-sdk": "5.0.3",
prefer to use each element or framework package from `lisk-commander`

2021-01-21 13:17 UTC, shuse2 approved these changes

2021-01-22 11:21 UTC, nazarhussain approved these changes

2021-01-22 11:23 UTC, merged