Generate genesis block - Closes #6074
LiskHQ/lisk-sdk pull request #6091
Opened 2021-01-25 23:31 UTC by Incede

### What was the problem?

This PR resolves #6074 

### How was it solved?

* Add base genesis block creation command in commander
* Add extended command in bootstrap template command
### How was it tested?

* Link lisk-commander inside the generated app `yarn link lisk-commander`
* Inside the app `./bin/run genesis-block:create --output mydir --accounts 10 --validators 12 --token-distribution 500`
* Added unit test

2021-01-27 09:44 UTC, shuse2 requested changes

2021-01-27 09:44 UTC, shuse2 commented on commander/src/bootstrapping/commands/genesis-block.ts
> +		const prepareNormalAccounts = (
this function can be defined outside?
also, probably better to use default account as base, and check token module is registered or not

2021-01-27 09:44 UTC, shuse2 commented on commander/src/bootstrapping/commands/genesis-block.ts
> +		const prepareValidatorAccounts = (
same as above, also username is not used.
`totalVotesReceived` and `sentVotes` are not needed for the genesis block as default

2021-01-27 09:44 UTC, shuse2 commented on commander/src/bootstrapping/commands/genesis-block.ts
> +				username: string;
username not needed

2021-01-27 09:44 UTC, shuse2 commented on commander/src/bootstrapping/commands/genesis-block.ts
> +			.map((_x, index) => ({ ...{ username: `account_${index}` }, ...createAccount() }));
username not required for default account

2021-01-27 09:44 UTC, shuse2 commented on commander/src/bootstrapping/commands/genesis-block.ts
> +		config: PartialApplicationConfig,
probably config not required?

2021-01-27 09:44 UTC, shuse2 commented on commander/src/bootstrapping/commands/genesis-block.ts
> +			default: 500,
500 is probably below min required balance

2021-01-27 09:57 UTC, Incede commented on commander/src/bootstrapping/templates/lisk-template-ts/templates/app/src/commands/genesis-block/create.ts
> +		registerModules(app);
could be, @nazarhussain suggested otherwise.

2021-01-27 10:06 UTC, nazarhussain commented on commander/src/bootstrapping/templates/lisk-template-ts/templates/app/src/commands/genesis-block/create.ts
> +		registerModules(app);
In current structure `registerModule` function take app instance and register custom modules in that application. We can revisit this approach if required.

2021-01-27 10:09 UTC, nazarhussain requested changes

2021-01-27 10:09 UTC, nazarhussain commented on commander/src/bootstrapping/commands/genesis-block.ts
> +				fs.writeJSONSync(resolve(configPath, 'genesis_block.json'), JSON.stringify(genesisBlock), {
This writes JSON object as string not the JSON object.

2021-01-27 10:09 UTC, nazarhussain commented on commander/src/bootstrapping/commands/genesis-block.ts
> +					JSON.stringify(delegateForgingInfo),
This writes JSON object as string not the JSON object.

2021-01-27 10:09 UTC, nazarhussain commented on commander/src/bootstrapping/commands/genesis-block.ts
> +				JSON.stringify(delegateForgingInfo),
This writes JSON object as string not the JSON object.

2021-01-27 10:24 UTC, nazarhussain requested changes

2021-01-27 10:24 UTC, nazarhussain commented on commander/src/bootstrapping/commands/genesis-block.ts
> +			default: '',
I suggest to use `config` a default output directory.

2021-01-27 15:32 UTC, shuse2 commented on commander/src/bootstrapping/commands/genesis-block/create.ts
> +		if (!('token' in defaultAccount)) {
prefer to use `getRegisteredModules` to check if the module is registered or not.
Also, ill create an issue to make it network agnostic

2021-01-27 17:11 UTC, shuse2 approved these changes

2021-01-28 10:01 UTC, nazarhussain approved these changes

2021-01-28 10:03 UTC, merged