Improve offline and online commander communication - Closes #6082
LiskHQ/lisk-sdk pull request #6094
Opened 2021-01-26 16:37 UTC by ManuGowda

### What was the problem?

This PR resolves #6082 

### How was it solved?

- Refactored base ipc
- Refactored bootstrapped commands

### How was it tested?

1. `cd lisk-sdk`; `yarn; yarn build`
2. `cd commander; yarn link`
3. `mkdir /tmp/test_lisk; cd /tmp/test_lisk`
4. `../lisk-sdk/commander/bin/run init`
5. `yarn link lisk-commander`
6. `./bin/run`
7, `npm run test`

2021-01-27 16:05 UTC, shuse2 requested changes
overall looks good to me, some questions regards to the usage of api client

2021-01-27 16:05 UTC, shuse2 commented on commander/src/bootstrapping/commands/transaction/sign.ts
> +const signTransactionOnline = async (
for online, is there any specific reason why `client.sign` cannot be used?

2021-01-27 16:05 UTC, shuse2 commented on commander/src/utils/transaction.ts
> +export const getApiClient = async (
```suggestion
export const getAPIClient = async (
```

2021-01-27 16:05 UTC, shuse2 commented on commander/src/bootstrapping/commands/transaction/create.ts
> +const createTransactionOnline = async (
why not use `client.create` function for online?

2021-01-28 10:20 UTC, shuse2 approved these changes

2021-01-28 10:24 UTC, nazarhussain approved these changes

2021-01-28 11:10 UTC, merged