Migrate commander mocha tests to jest - Closes #6105
LiskHQ/lisk-sdk pull request #6109
Opened 2021-02-03 14:02 UTC by ManuGowda

### What was the problem?

This PR resolves #6105 

### How was it solved?

- Update unit test files to .spec.ts
- Fix message sign command to return publicKey and signature as hex string
- Cleanup mocha configuration and dependencies

### How was it tested?

- All unit tests are migrated to jest and pipeline is updated

2021-02-03 14:11 UTC, shuse2 requested changes

2021-02-03 14:11 UTC, shuse2 commented on commander/src/commands/account/create.ts
> +export { AccountCreateCommand } from '../../index';
instead of calling index, it should call original position

2021-02-03 14:11 UTC, shuse2 commented on commander/test/tsconfig.json
> +	"include": ["../src/**/*", "./**/*", "../package.json", "../config/**/*.json"]
do we need `*.json`?

2021-02-03 16:56 UTC, shuse2 approved these changes

2021-02-04 13:40 UTC, mitsuaki-u approved these changes

2021-02-04 13:41 UTC, merged