Improve init command description log messages - Closes #6133
LiskHQ/lisk-sdk pull request #6142
Opened 2021-02-09 16:58 UTC by ManuGowda

### What was the problem?

This PR resolves #6133 

### How was it solved?

- Fixed description according to expectation

### How was it tested?

- Build and run init command

2021-02-09 17:01 UTC, shuse2 requested changes

2021-02-09 17:01 UTC, shuse2 commented on commander/src/commands/init.ts
> +		'Commands relating to bootstrapping a blockchain application or plugin using lisk-sdk.';
This topic description should be in the package.json?
For this specific command, it should be only showing about this command.
Also, product name is `Lisk SDK`

2021-02-10 08:11 UTC, mitsuaki-u approved these changes

2021-02-10 08:47 UTC, shuse2 approved these changes

2021-02-10 08:48 UTC, merged