Remove blockchain download command - Closes #6164
LiskHQ/lisk-sdk pull request #6165
Opened 2021-02-11 15:09 UTC by shuse2

### What was the problem?

This PR resolves #6164 

### How was it solved?

- Remove download command since it's specific to Lisk-core

### How was it tested?

n/a

2021-02-11 15:47 UTC, ManuGowda reviewed
you need to remove the index.js file and extended command in template

2021-02-11 16:55 UTC, nazarhussain requested changes
LGTM other than what @ManuGowda  highlighted.

2021-02-12 08:40 UTC, ManuGowda approved these changes
maybe you need to remove from here too `commander/src/index.ts`

2021-02-12 10:17 UTC, nazarhussain approved these changes

2021-02-12 10:32 UTC, merged