Codec validateSchema should check for the field number existence - Closes #6191
LiskHQ/lisk-sdk pull request #6215
Opened 2021-03-10 14:55 UTC by Incede

### What was the problem?

This PR resolves #6191 

### How was it solved?

* Check properties in schema to include `fieldNumber`

### How was it tested?

* Tested manually using custom schema in test cases

2021-03-10 15:13 UTC, shuse2 requested changes

2021-03-10 15:13 UTC, shuse2 commented on elements/lisk-codec/src/codec.ts
> +		Object.values(properties).forEach(property => {
Prefer to use `for...of` as it is slow although this only runs once so it would not make big difference

2021-03-10 15:13 UTC, shuse2 commented on elements/lisk-codec/src/codec.ts
> +			if (!('fieldNumber' in property)) {
field number can exist in the nested properties, too. 
Did you consider updating `elements/lisk-validator/src/lisk_meta_schema.ts` which is executed in above L63?

2021-03-11 09:02 UTC, shuse2 requested changes
Please add unit tests to check if the root and nested field number check is done correctly

2021-03-11 09:02 UTC, shuse2 commented on elements/lisk-codec/src/codec.ts
> +				if (!('fieldNumber' in property)) {
I think we want to check `fieldNumber` exists and the value in the range 1 to 18’999. (https://github.com/LiskHQ/lips/blob/master/proposals/lip-0027.md#field-name-and-field-number)

2021-03-11 13:21 UTC, ishantiw approved these changes

2021-03-11 16:06 UTC, shuse2 requested changes
other than the dependency usage LGTM

2021-03-11 16:06 UTC, shuse2 commented on elements/lisk-codec/package.json
> +		"lodash.clonedeep": "4.5.0",
Please use cloneDeep from `@liskhq/lisk-utils`

2021-03-11 16:56 UTC, shuse2 approved these changes

2021-03-11 17:10 UTC, merged