Fund tokens with faucet plugin - Closes #6138
LiskHQ/lisk-sdk pull request #6227
Opened 2021-03-11 10:20 UTC by mitsuaki-u

### What was the problem?

This PR resolves #6138 

### How was it solved?

- Added dependencies
- Added fund tokens action
- Added create transfer transaction method
- Added relevant unit tests

### How was it tested?

Run unit test for faucet plugin

2021-03-11 14:34 UTC, shuse2 requested changes

2021-03-11 14:34 UTC, shuse2 commented on framework-plugins/lisk-framework-faucet-plugin/src/plugin/faucet_plugin.ts
> +import { Transaction } from '@liskhq/lisk-chain';
Transaction is not needed in the `plugin`

2021-03-11 14:34 UTC, shuse2 commented on framework-plugins/lisk-framework-faucet-plugin/src/plugin/faucet_plugin.ts
> +		const transferAssetInfo = this.schemas.transactionsAssets.find(
you can create api client using channel, and create and send the transaction using the client

2021-03-11 14:34 UTC, shuse2 commented on framework-plugins/lisk-framework-faucet-plugin/test/unit/plugin/fund.spec.ts
> +	it('should error if action input is invalid', async () => {
maybe these test couldve been covered in functional tests?

2021-03-11 14:34 UTC, shuse2 commented on framework-plugins/lisk-framework-faucet-plugin/package.json
> +		"@liskhq/lisk-chain": "^0.2.0",
with below comments, this will not be needed

2021-03-12 08:58 UTC, ishantiw approved these changes

2021-03-12 13:03 UTC, shuse2 approved these changes

2021-03-12 13:03 UTC, merged