Improve genesis block creation utility provided by "testing" in framework - Closes #6258
LiskHQ/lisk-sdk pull request #6261
Opened 2021-03-17 15:56 UTC by ManuGowda

### What was the problem?

This PR resolves #6258 

### How was it solved?

- Remove unwanted fixtures and update tests and utils
- createGenesisBlock util will have default values except modules

### How was it tested?

- Updated tests

2021-03-18 13:02 UTC, shuse2 commented on framework/src/testing/create_genesis_block.ts
> +	if (!params.modules.includes(DPoSModule)) {
why do we need this?

2021-03-19 09:49 UTC, shuse2 approved these changes

2021-03-19 13:09 UTC, Incede commented on framework/src/testing/app_env.ts
> -		}
So now with this change, if someone initializes AppEnv with empty modules `[]` as input and then start application with `AppEnv.startApplication()` how will the application start (and/or forge blocks) without `DPos` module ?

2021-03-19 13:19 UTC, Incede requested changes

2021-03-19 13:19 UTC, Incede commented on framework/src/testing/fixtures/accounts.ts
> +const getDelegateFromDefaultConfig = (address: Buffer) => {
I am not sure if this function should be in `fixtures`. maybe move it to `utils`.
Same for other functions below.

2021-03-22 12:21 UTC, shuse2 commented on framework-plugins/lisk-framework-http-api-plugin/test/functional/utils/application.ts
> +	const dataPath = join(rootPath.replace('~', homedir()), label);
is this handling correct? homedir/label is not the data path

2021-03-22 12:21 UTC, shuse2 commented on framework-plugins/lisk-framework-http-api-plugin/test/functional/utils/application.ts
>  			maxInboundConnections: 0,
maybe `maxInboundConnection: 0` can be default, and rpc, forging settings

2021-03-22 14:37 UTC, Incede approved these changes

2021-03-23 07:16 UTC, merged