Add Dashboard button and icon button component - Closes #6225 button component
LiskHQ/lisk-sdk pull request #6277
Opened 2021-03-24 14:21 UTC by mitsuaki-u

### What was the problem?

This PR resolves #6225 

### How was it solved?

- Added Button component
- Added IconButton component
- Added styiling

### How was it tested?

Check mainpage of dashboard

2021-03-24 14:27 UTC, shuse2 requested changes

2021-03-24 14:27 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Button/Button.module.scss
> +	background: #4070F4;
this should use the constant defined

2021-03-24 14:27 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/IconButton/index.tsx
> +	const size = props.size ?? 'm';
Icon button should use the icon component

2021-03-24 14:27 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/IconButton/IconButton.module.scss
> +@import '../../styles/constants';
this file shouldn't be required if Icon component is used

2021-03-24 14:27 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Button/Button.module.scss
> +	border-radius: 3px;
there are several properties that needs to be handled
https://github.com/LiskHQ/lisk-sdk/blob/development/framework-plugins/lisk-framework-faucet-plugin/src/ui/app.module.scss#L146-L169

2021-03-24 14:27 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Button/Button.module.scss
> +	left: 20px;
left/top should be required?

2021-03-24 14:27 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Button/index.tsx
> +	return <button className={`${styles.button} ${styles[`button-${size}`]}`} onClick={onSubmit}>{name}</button>;
name should use the `Text` component

2021-03-24 14:27 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Button/Button.module.scss
> +		&.button-s {
these are not required i think

2021-03-25 09:35 UTC, nazarhussain requested changes

2021-03-25 09:35 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Button/index.tsx
> +			<Text>{name}</Text>
Why we need `Text` component here? HTML `button` can wrap the text itself.

2021-03-25 09:35 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Button/index.tsx
> +		<button className={`${styles.button} ${styles[`button-${size}`]}`} onClick={onSubmit}>
I am not sure why you need to set `onClick` to an empty handler. But if you want to disable any default interaction you should use 

https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault

2021-03-25 09:35 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Button/index.tsx
> +	name: string;
The issue didn't mentioned to have a `name` prop to use as button text. Rather as normal React component `Button` should just render the `children` prop.

2021-03-25 09:35 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/IconButton/index.tsx
> +		<div className={styles['icon-button']} onClick={onSubmit}>
Here you should use the `Button` component and add `Icon` as its children along with `Text`.

2021-03-25 09:35 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/pages/MainPage.tsx
> +			<Button name={'Button'} size={'m'} />
Its usage should be`<Button size={'m'}>Button</Button>

2021-03-25 09:35 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/IconButton/index.tsx
> +	name: string;
As per the issue the prop name is `icon` not the `name`.

2021-03-25 14:38 UTC, nazarhussain approved these changes

2021-03-25 15:13 UTC, shuse2 approved these changes

2021-03-25 15:13 UTC, merged