Create react component for dialogs - Closes #6233
LiskHQ/lisk-sdk pull request #6288
Opened 2021-03-30 10:36 UTC by nazarhussain

### What was the problem?

This PR resolves #6233

### How was it solved?

- Created Box component 
- Created Grid component 
- Created MessageDialog component 
- Created AccountDialog component 
- 

### How was it tested?

- Added components to main page and tested manually

2021-03-30 16:08 UTC, shuse2 requested changes
Looks good in general. Some points are
- DIalog in small screen is not full height
- NodeInfo popup should be 1 info per row in small size
- Account passphrase and public key copy changes the passphrase word position
- 
maybe some points shoudlve been raised in the privious issue

2021-03-31 10:47 UTC, nazarhussain commented
@shuse2 Created issue to fix the CopiableText https://github.com/LiskHQ/lisk-sdk/issues/6291 Rest of the points are covered in this PR.

2021-03-31 12:22 UTC, ManuGowda reviewed
PR looks good to me, two things:
- the peer info icons seems to be different from figma
- the node info has grid seems to be speared at base fees grid in comparison to figma

2021-03-31 13:56 UTC, ishantiw approved these changes

2021-03-31 14:02 UTC, shuse2 approved these changes

2021-03-31 14:53 UTC, merged