Create react base table component - Closes #6290, 6235, 6236
LiskHQ/lisk-sdk pull request #6304
Opened 2021-04-06 13:45 UTC by ManuGowda

### What was the problem?

This PR resolves #6290, 6235, 6236

### How was it solved?

- Created base table container
- Implemented Recent Blocks, Recent Transactions and Unconfirmed Transactions widgets

### How was it tested?

- Build and run dashboard `npm run start:web`

2021-04-06 16:12 UTC, shuse2 requested changes

2021-04-06 16:12 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Widgets/BlockWidget.tsx
> +	widgetTitle: string;
this can be simply `title` as the component name says it is widget

2021-04-06 16:12 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Widgets/BlockWidget.tsx
> +	scrollbar?: boolean;
does it need this `scrollbar` option on this widget? it should be always true?

2021-04-06 16:12 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Widgets/TransactionWidget.tsx
> +	widgetTitle: string;
same as above

2021-04-06 16:12 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Widgets/TransactionWidget.tsx
> +	if (props.transactions.length === 0) return null;
component shouldnt return `null` value. it should at least return `<div />`.
but why when length is zero, it's trying to not to display anything?

2021-04-07 08:17 UTC, nazarhussain requested changes

2021-04-07 08:17 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Grid/Grid.module.scss
> +
I am ok with having this additional option. But if you keep the number of columns in the row consistent to 12 they will never wrap anyway. If you think that's fine then we can remove that additional option.

2021-04-07 08:17 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Table/Table.module.scss
> +	width: 560px;
Please don't fix the width of table, as its a generic presentational component and can be used in different cases. Let it adjust as per container.

2021-04-07 08:17 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Table/Table.module.scss
> +	}
As this style is reused, we can extract it to be a mixin.

2021-04-07 14:16 UTC, nazarhussain requested changes

2021-04-07 14:16 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Grid/index.tsx
> +	rowNoWrap?: boolean;
```suggestion
```

2021-04-07 14:18 UTC, nazarhussain approved these changes

2021-04-08 11:27 UTC, shuse2 approved these changes

2021-04-08 11:27 UTC, merged