Rename cryptography function name regarding base32 address - Closes #6283
LiskHQ/lisk-sdk pull request #6315
Opened 2021-04-12 07:10 UTC by nazarhussain

### What was the problem?

This PR resolves #6283

### How was it solved?

- Renamed original Base32 address functions to Lisk32 address
- Linked Base32 address functions originals 
- Marked these Base32 address functions as deprecated 
- Updated tests 

### How was it tested?

- Run all tests

2021-04-12 14:15 UTC, shuse2 requested changes
Changes LGTM. There are several usage of base32 function in commander, so we can update those as well?

2021-04-12 15:02 UTC, mitsuaki-u approved these changes
Changes LGTM

2021-04-13 07:45 UTC, nazarhussain commented
@shuse2 Tests are updated.

2021-04-13 07:55 UTC, shuse2 approved these changes

2021-04-13 09:44 UTC, merged