Create react component for call action widget - Closes #6238
LiskHQ/lisk-sdk pull request #6323
Opened 2021-04-14 08:50 UTC by Incede

### What was the problem?

This PR resolves #6238 

### How was it solved?

* Create `Call action` widget component
* Add sample to main page

### How was it tested?
* Add sample to main page

2021-04-15 15:17 UTC, shuse2 requested changes

2021-04-15 15:17 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/widgets/CallActionWidget.tsx
> +	}, [props.actions]);
i think this doesn't need to be in the `useEffect`. listOptions can be directly initialized with the props.
setSelectedActions is triggered by onchange of selectInput?

2021-04-21 15:52 UTC, shuse2 approved these changes

2021-04-21 16:01 UTC, mitsuaki-u approved these changes

2021-04-21 18:01 UTC, merged