Create state to store the API responses for dashboard - Closes #6241, #6242, #6243
LiskHQ/lisk-sdk pull request #6326
Opened 2021-04-15 10:51 UTC by nazarhussain

### What was the problem?

This PR resolves #6241, #6242, #6243

### How was it solved?

- Created react states to store data
- Created API client to and connect to backend
- Linked states to components 

### How was it tested?

- Manually tested bu running lisk-core with `--api-ws`

2021-04-16 12:58 UTC, shuse2 requested changes

2021-04-16 12:58 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/utils/index.ts
> +	const newBlocks = [...blocks, newBlock].slice(-1 * MAX_BLOCKS) as Block[];
order of block should be height desc

2021-04-16 12:58 UTC, shuse2 commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/utils/index.ts
> +	return [...unconfirmedTransactions, transaction].slice(-1 * MAX_TRANSACTIONS) as Transaction[];
the latest transaction should be on the top

2021-04-16 13:00 UTC, ManuGowda reviewed
LGTM

2021-04-16 13:30 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/pages/MainPage.tsx
> +	const getClient = () => client as apiClient.APIClient;
No its not but because of state don't have an initial value so it complaints of may be undefined.

2021-04-19 09:14 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/types.ts
> +export interface GenesisConfig {
I just wanted not to create `framework` dependency in the UI files.

2021-04-19 09:20 UTC, ManuGowda approved these changes

2021-04-19 09:22 UTC, shuse2 approved these changes

2021-04-19 11:31 UTC, merged