Fix dashboard styles - Closes #6364
LiskHQ/lisk-sdk pull request #6366
Opened 2021-04-30 16:54 UTC by shuse2

### What was the problem?

This PR resolves #6364 

### How was it solved?

Fix the styling mentioned in the issues

### How was it tested?

```
npm run start:web
```
and check the problem does not exist and other styles are not affected

2021-05-03 07:31 UTC, nazarhussain requested changes

2021-05-03 07:31 UTC, nazarhussain commented on framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Grid/index.tsx
> +		styles.root,
```suggestion
```

There is no `.root` style for the grid.

2021-05-03 08:11 UTC, nazarhussain approved these changes

2021-05-04 07:05 UTC, ManuGowda approved these changes

2021-05-04 07:05 UTC, merged