Create database interface for sparse Merkle tree - Closes #6486
LiskHQ/lisk-sdk pull request #6514
Opened 2021-07-01 08:03 UTC by Incede

### What was the problem?

This PR resolves #6486 

### How was it solved?

Defined interface for `get` `set` `del` operations on a generic key-value store

### How was it tested?

All operations needed are present in the interface

2021-07-01 15:52 UTC, shuse2 requested changes

2021-07-01 15:52 UTC, shuse2 commented on elements/lisk-tree/src/sparse_merkle_tree/types.ts
> +export interface KeyValueStore {
```suggestion
export interface Database {
```
I added the interface as `Database` on standard merkle tree, so let's keep it the same

2021-07-02 07:59 UTC, nazarhussain approved these changes

2021-07-02 08:25 UTC, shuse2 approved these changes

2021-07-02 13:56 UTC, merged