Create consensus component - Closes #6560
LiskHQ/lisk-sdk pull request #6583
Opened 2021-07-15 10:18 UTC by shuse2

### What was the problem?

This PR resolves #6560 

### How was it solved?

- Move synchronizer to consensus domain
- Move transport logic related to synchronizer to under consensus
- Create consensus component using processor code and the state machine

### How was it tested?

- Adding unit tests

### Additional information
- This needs real state store implementation and block header implementation to work (#6564 and #6581 )

2021-07-19 14:05 UTC, ishantiw requested changes

2021-07-19 14:05 UTC, ishantiw commented on framework/test/unit/node/consensus/endpoint.spec.ts
> +			[...new Array(DEFAULT_BLOCKS_FROM_IDS_RATE_LIMIT_FREQUENCY + 1)].map(async () =>
maybe consistently follow `ArrangeActAssert` in the test, also at other places?

2021-07-19 14:05 UTC, ishantiw commented on framework/test/unit/node/consensus/endpoint.spec.ts
> +			it('should return the result', async () => {
```suggestion
			it('should return highest common block header', async () => {
```

2021-07-19 14:07 UTC, shuse2 commented on framework/src/node/consensus/endpoints.ts
> +export class Endpoint {
true. consensus API will be like `reducer` so maybe `P2PEndpoint`?

2021-07-19 14:15 UTC, ishantiw commented on framework/src/node/consensus/endpoints.ts
> +export class Endpoint {
`P2PEndpoint ` or `NetworkEndpoint` both sounds better

2021-07-20 12:00 UTC, ManuGowda commented on framework/src/node/consensus/synchronizer/block_synchronization_mechanism.ts
> +				'Previous tip of the chain has preference over current tip. Restoring chain from temp table',
```suggestion
				'Previous tip of the chain has preference over current tip. Restoring chain from temp table.',
```

2021-07-20 12:06 UTC, ManuGowda reviewed
LGTM, if its not a huge problem can we try to move the syncronizer code preserving the history? useful for the future reference

2021-07-20 12:06 UTC, ManuGowda commented on framework/test/unit/node/consensus/consensus.spec.ts
> +		it('should veryfy block using state machine', () => {
```suggestion
		it('should verify block using state machine', () => {
```

2021-07-23 09:26 UTC, shuse2 commented on framework/src/node/consensus/synchronizer/fast_chain_switching_mechanism.ts
> +			'Requesting blocks within ID range from peer',
Here peerID is already logged in the above object

2021-07-23 12:39 UTC, shuse2 commented on framework/src/node/consensus/constants.ts
> +export const NETWORK_EVENT_POST_BLOCK = 'postBlock';
this is the rpc method name, so we cannot cange or capital would also be strange

2021-07-23 13:42 UTC, ManuGowda approved these changes

2021-07-26 16:08 UTC, ishantiw approved these changes

2021-07-26 17:42 UTC, merged