Create event queue - Closes #6563
LiskHQ/lisk-sdk pull request #6599
Opened 2021-07-26 10:18 UTC by ManuGowda

### What was the problem?

This PR resolves #6563

### How was it solved?

- Implemented event queue 

### How was it tested?

- Added unit tests

2021-07-26 11:17 UTC, shuse2 requested changes

2021-07-26 11:17 UTC, shuse2 commented on framework/test/unit/node/state_machine/event_queue.spec.ts
> +	// eslint-disable-next-line @typescript-eslint/require-await
if it's not await, let's not make it await

2021-07-26 12:38 UTC, shuse2 approved these changes

2021-07-27 10:12 UTC, ishantiw approved these changes

2021-07-27 14:55 UTC, merged