Update domain lisk.io to lisk.com
LiskHQ/lisk-sdk pull request #6608
Opened 2021-08-02 06:39 UTC by ManuGowda

### What was the problem?

- The lisk domain was changed from lisk.io to lisk.com, which was not reflected in codebase

### How was it solved?

- Updated all the domain references

### How was it tested?

- Click on new domain links and check if they navigate to correct page

2021-08-02 15:50 UTC, shuse2 reviewed
looks good in general

2021-08-02 15:50 UTC, shuse2 commented on elements/lisk-client/README.md
> +[lisk documentation site]: https://lisk.com/documentation/lisk-sdk/references/lisk-elements/index.html
I think we dont need `index.html`? same for other places

2021-08-03 19:59 UTC, shuse2 approved these changes

2021-08-04 15:41 UTC, Incede requested changes

2021-08-04 15:41 UTC, Incede commented on sdk/README.md
> +Please be advised, although we have stabilized the architecture of SDK, we cannot guarantee blockchain created with the beta release of the Lisk SDK will remain compatible with our planned release ca
```suggestion
Please be advised, although we have stabilized the architecture of SDK, we cannot guarantee a blockchain created with the beta release of the Lisk SDK will remain compatible with our planned release candidates.
```

2021-08-04 15:41 UTC, Incede commented on elements/README.md
> +Lisk Elements is a collection of libraries, each of them implementing some form of blockchain application functionality such as cryptography, transactions, p2p, etc. Each library is designed to be co
Any reason for changing this to `research.lisk.com` ?
I don't see anything that goes by `Lisk Protocol` here.

How about `https://lisk.com/documentation/lisk-sdk/protocol/index.html`

2021-08-04 15:41 UTC, Incede commented on elements/lisk-api-client/README.md
> +[lisk documentation site]: https://lisk.com/documentation/lisk-sdk/references/lisk-elements
Wouldn't it be better if we link to the exact sub-section ?
Same for all other readme's.
```suggestion
[lisk documentation site]: https://lisk.com/documentation/lisk-sdk/references/lisk-elements/api-client.html
```

2021-08-04 15:41 UTC, Incede commented on framework-plugins/lisk-framework-dashboard-plugin/README.md
> +[lisk documentation site]: https://lisk.com/documentation/lisk-sdk/references/lisk-elements
Why are we linking to `elements` docs for `framework-plugins` ?

2021-08-04 16:38 UTC, ManuGowda commented
Good catch @Incede

2021-08-05 09:03 UTC, Incede approved these changes

2021-08-05 09:04 UTC, merged