Create fee module class - Closes #6692
LiskHQ/lisk-sdk pull request #6700
Opened 2021-08-30 17:15 UTC by mitsuaki-u

### What was the problem?

This PR resolves #6692

### How was it solved?

🌱 81db6898d2b8aa0d7964d921489e1c4976751dae

-  Create fee module class
-  Add `addDependencies` method to interact with token module
-  Add configuration options
-  Add `verifyTransaction` and `beforeTransactionExecution` hooks

🌱 16474ee48e2609cc0f88c300e20d04e21464b294

- Add schemas for configuration inputs

### How was it tested?

To be added later.

2021-08-30 20:11 UTC, shuse2 requested changes
one minor comment but LGTM

2021-08-30 20:11 UTC, shuse2 commented on framework/src/modules/fee/module.ts
> +	public id = 11;
this should be `MODULE_ID_FEE` defined in the constants

2021-08-31 08:09 UTC, shuse2 approved these changes

2021-08-31 08:28 UTC, ManuGowda commented on framework/src/modules/fee/types.ts
> +		id: { chainID: number; localID: number },
```suggestion
		feeTokenID: FeeTokenID,
```

2021-08-31 08:28 UTC, ManuGowda commented on framework/src/modules/fee/types.ts
> +		id: { chainID: number; localID: number },
```suggestion
		feeTokenID: FeeTokenID,
```

2021-08-31 08:28 UTC, ManuGowda commented on framework/src/modules/fee/types.ts
> +	feeTokenID: {
you can extract this to `FeeTokenID` interface
```
interface FeeTokenID {
  chainID: number;
  localID: number;
}
```

then

`feeTokenID: FeeTokenID`

2021-08-31 13:01 UTC, ManuGowda approved these changes

2021-08-31 13:01 UTC, merged