Implement DPoS unlocking command - Closes #6726
LiskHQ/lisk-sdk pull request #6870
Opened 2021-10-29 15:33 UTC by mitsuaki-u

### What was the problem?

This PR resolves #6726 

### How was it solved?

Implemented unlock command and test following scenarios:

- [x] When non self-voted non punished account waits 2000 blocks
- [x] When non self-voted non punished account did not wait 2000 blocks
- [x] When self-voted non punished account waits 260000 blocks
- [x] When self-voted non punished account did not wait 260000 blocks
- [x] When non self-voted punished account has waited pomHeight + 260000 and unvoteHeight + 2000 blocks
- [x] When non self-voted punished account has waited pomHeight + 260000 blocks but not waited for unlockHeight + 2000 blocks
- [x] When non self-voted punished account has not waited pomHeight + 260,000 blocks but waited unlockHeight + 2000 blocks
- [x]  When non self-voted punished account has not waited pomHeight + 260,000 blocks but waited unvoteHeight + 2000 blocks and pomHeight is more than unvoteHeight + 2000 blocks
- [x]  When non self-voted punished account has not waited pomHeight + 260000 blocks but waited unvoteHeight + 2000 blocks and pomHeight is equal to unvoteHeight + 2000 blocks
- [x] When self-voted punished account waits 780000 blocks and waits unvoteHeight + 260000 blocks since pomHeight
- [x] When self-voted punished account waits 780000 blocks and but did not wait unvoteHeight + 260000 blocks since pomHeight
- [x] When self-voted punished account has not waited 780000 blocks and waits unvoteHeight + 260000 blocks since pomHeight
- [x] When self-voted punsished account has not waited pomHeight + 260000 blocks but waited unvoteHeight + 2000 blocks and pomHeight is more than unvoteHeight + 2000 blocks

### How was it tested?

Added unit tests

2021-11-02 16:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LiskHQ/lisk-sdk?pullRequest=6870) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LiskHQ/lisk-sdk?pullRequest=6870) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LiskHQ/lisk-sdk?pullRequest=6870) it.</sub>

2021-11-04 09:55 UTC, shuse2 requested changes

2021-11-04 09:55 UTC, shuse2 commented on framework/test/unit/modules/dpos_v2/commands/unlock.spec.ts
> +			// This covers scenario: has not waited pomHeight + 260000 blocks but waited unvoteHeight + 2000 blocks and pomHeight is equal to unvoteHeight + 2000 blocks
```suggestion
			// This covers scenario: has not waited pomHeight + 260,000 blocks but waited unvoteHeight + 2000 blocks and pomHeight is equal to unvoteHeight + 2000 blocks
```

2021-11-04 09:55 UTC, shuse2 commented on framework/test/unit/modules/dpos_v2/commands/unlock.spec.ts
> +		header = new BlockHeader({
you can use testing `createFakeBlockHeader`

2021-11-04 09:55 UTC, shuse2 commented on framework/test/unit/modules/dpos_v2/commands/unlock.spec.ts
> +		lastBlockHeight = 8760000;
```suggestion
		blockHeight = 8760000;
```
this height is currently being executed

2021-11-04 09:55 UTC, shuse2 commented on framework/src/modules/dpos_v2/utils.ts
> -export const isCurrentlyPunished = (height: number, pomHeights: ReadonlyArray<number>): boolean => {
this is still used in other function, so it should be kept

2021-11-04 09:55 UTC, shuse2 commented on framework/test/unit/modules/dpos_v2/commands/unlock.spec.ts
> +					pomHeights: [lastBlockHeight - 1],
just note here if `lastBlockHeight - 1` will make `unvoteHeight` to be within punishment `lastPomHeight < unlockingObject.unvoteHeight + WAIT_TIME_SELF_VOTE` period.

2021-11-04 09:55 UTC, shuse2 commented on framework/src/modules/dpos_v2/utils.ts
> +		delayedAvailability = 260000;
Prefer to use constants

2021-11-04 18:11 UTC, shuse2 approved these changes
LGTM! Good job 🚀

2021-11-05 12:20 UTC, ishantiw approved these changes
Great work @mitsuaki-u 👏

2021-11-05 15:36 UTC, merged