Update block verification - Closes #6754
LiskHQ/lisk-sdk pull request #6872
Opened 2021-11-02 02:58 UTC by ishantiw

### What was the problem?

This PR resolves #6754

### How was it solved?

🌱 Add block verification b34b8bd
- Verify the timestamp, height, previousBlockID, generatorAddress, maxHeightPrevoted, maxHeightGenerated, and signature properties
- Update interface for bft and validator module API

✅ Add all tests for block verification 2ec8bba

### How was it tested?

`npm run test:unit consensus.spec`

2021-11-02 11:10 UTC, shuse2 requested changes

2021-11-02 12:13 UTC, shuse2 approved these changes
Great  job 🚀

2021-11-02 16:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LiskHQ/lisk-sdk?pullRequest=6872) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LiskHQ/lisk-sdk?pullRequest=6872) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LiskHQ/lisk-sdk?pullRequest=6872) it.</sub>

2021-11-04 19:08 UTC, Incede approved these changes
Looks good, one minor rephrasing suggestion.

2021-11-04 19:51 UTC, Incede commented on framework/src/node/consensus/consensus.ts
> +				)} of the block with id: ${block.header.id.toString('hex')}`,
```suggestion
				`Generator with address ${block.header.generatorAddress.toString('hex',)} of the block with id: ${block.header.id.toString('hex')}` is ineligible to generate block for the current slot,
```

2021-11-04 20:41 UTC, merged