Implement report misbehavior command for DPoS module - Closes #6727
LiskHQ/lisk-sdk pull request #6880
Opened 2021-11-04 16:41 UTC by Incede

### What was the problem?

This PR resolves #6727 

### How was it solved?

Refactor existing logic to implement report misbehavior command as per the LIP specifications

### How was it tested?

Refactor existing unit tests per the new code

2021-11-04 16:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LiskHQ/lisk-sdk?pullRequest=6880) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LiskHQ/lisk-sdk?pullRequest=6880) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LiskHQ/lisk-sdk?pullRequest=6880) it.</sub>

2021-11-04 22:01 UTC, shuse2 requested changes

2021-11-04 22:01 UTC, shuse2 commented on framework/test/unit/modules/dpos_v2/commands/pom.spec.ts
> +			updatedDelegateAccount.name = '';
instead of emptying the name, it should use non-existing key for the delegateStore

2021-11-04 22:01 UTC, shuse2 commented on framework/test/unit/modules/dpos_v2/commands/pom.spec.ts
> +		it('should reward the sender with last block reward if delegate have enough balance', async () => {
```suggestion
		it('should reward the sender with 1LSK if delegate have enough balance', async () => {
```

2021-11-04 22:01 UTC, shuse2 commented on framework/test/unit/modules/dpos_v2/commands/pom.spec.ts
> +	const lastBlockReward = LAST_BLOCK_REWARD;
```suggestion
	const reportPunishmentReward = LAST_BLOCK_REWARD;
```

2021-11-05 10:46 UTC, shuse2 approved these changes
LGTM! GJ 🎉

2021-11-05 15:27 UTC, mitsuaki-u approved these changes
All scenario is covered, GJ! 🎉

2021-11-05 17:50 UTC, merged