Create certificate generation utils and CommitPool class - Closes #6838 & 6843
LiskHQ/lisk-sdk pull request #6913
Opened 2021-11-18 12:37 UTC by ishantiw

### What was the problem?

This PR resolves #6838 & #6839

### How was it solved?

- Create certificate utils #6838 and CommitPool class #6843 
- Add schemas
- Add constants
- Add types
- Add test files

### How was it tested?

- Check if all the files, types, constants and function declarations are present

2021-11-18 13:51 UTC, Incede approved these changes

2021-11-19 07:52 UTC, shuse2 requested changes

2021-11-19 07:52 UTC, shuse2 commented on framework/src/node/consensus/certificate_generation/commit_pool.ts
> +	private _aggregateSingleCommits(_singleCommits: SingleCommit[]) {}
return type definition is missing, but can be added later when implementing

2021-11-19 07:52 UTC, shuse2 commented on framework/src/node/consensus/certificate_generation/schema.ts
> +	required: ['height', 'aggregationBits', 'certificateSignature'],
`$id` is missing

2021-11-19 11:42 UTC, shuse2 approved these changes

2021-11-19 12:15 UTC, merged