Add genesis block handling for auth module - Closes #6921
LiskHQ/lisk-sdk pull request #6927
Opened 2021-11-21 07:36 UTC by shuse2

### What was the problem?

This PR resolves #6921

### How was it solved?

- Add genesis block handling for auth module

### How was it tested?

- Added unit tests

2021-11-22 21:38 UTC, Incede approved these changes

2021-11-24 08:24 UTC, mehmetegemen requested changes

2021-11-24 08:24 UTC, mehmetegemen commented on framework/test/unit/modules/auth/auth_module.spec.ts
> +							storeKey: getRandomBytes(8),
isn't it better to put valid 20 byte addresses here(and many other places) to isolate the incorrect test case?

2021-11-24 08:24 UTC, mehmetegemen commented on framework/test/unit/modules/auth/auth_module.spec.ts
> +								mandatoryKeys: new Array(33)
Ishan's `Array.from({ length: 33 }, _ => getRandomBytes(32))` trick is really neat, you might consider it

2021-11-24 08:58 UTC, mehmetegemen approved these changes

2021-11-24 09:29 UTC, merged