Implement signCertificate for CommitPool - Closes #6840
LiskHQ/lisk-sdk pull request #6934
Opened 2021-11-22 16:46 UTC by mitsuaki-u

### What was the problem?

This PR resolves #6840 

### How was it solved?

- 🌱 Add signCertificaste
- 🌱 Add tests

### How was it tested?

Added unit test

2021-11-22 19:24 UTC, shuse2 requested changes

2021-11-22 19:24 UTC, shuse2 commented on framework/src/node/consensus/certificate_generation/utils.ts
> +	const { aggregationBits, ...certificateWithoutAggregationBits } = certificate;
signature also should be removed from the certificate

2021-11-22 19:24 UTC, shuse2 commented on framework/test/unit/node/consensus/certificate_generation/utils.spec.ts
> +			expect(signCertificate(privateKey, networkIdentifier, certificate)).toEqual(signature);
it's better to input the certificate with `signature` and `aggregationBits`, and make sure those are not included in the message

2021-11-23 08:54 UTC, shuse2 approved these changes
LGTM, just there are some conflicts

2021-11-23 12:09 UTC, Incede approved these changes

2021-11-23 13:29 UTC, merged