Add rate limit reset job in generator and consensus - Closes #6940
LiskHQ/lisk-sdk pull request #6977
Opened 2022-01-13 11:39 UTC by ishantiw

### What was the problem?

This PR resolves #6940 

### How was it solved?

♻️ Add start/stop job for rateLimit reset job 870f9d631b55cb84418287a1e97e0b0c2f492ace

### How was it tested?

`npm run test:unit` under `framework`

2022-01-13 15:39 UTC, shuse2 requested changes

2022-01-13 15:39 UTC, shuse2 commented on framework/src/node/consensus/consensus.ts
> +		this._endpoint.start();
I think adding `start` in consensus and calling it from node would be more consistent

2022-01-14 09:14 UTC, shuse2 approved these changes

2022-01-14 10:09 UTC, mitsuaki-u approved these changes
Other than @shuse2 comment and unit test LGTM

2022-01-14 12:37 UTC, merged