Update current phase of Lisk SDK - Closes 6997
LiskHQ/lisk-sdk pull request #7031
Opened 2022-02-22 12:06 UTC by ishantiw

### What was the problem?

This PR resolves #6997 

### How was it solved?

- Updated phase section of the readme

### How was it tested?

n/a

2022-02-23 07:23 UTC, shuse2 requested changes
Looks good to me, just minor suggestion

2022-02-23 07:23 UTC, shuse2 commented on sdk/README.md
> +We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk
```suggestion
We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk.com/roadmap) that brings the [Lisk interoperability solution](https://lisk.com/blog/research/lisk-interoperability-solution-published) which is fully researched and all Lisk Improvement Proposals (LIPs) are published and currently being actively developed. It consists of 8 roadmap objectives,
```

2022-02-23 07:23 UTC, shuse2 commented on sdk/README.md
> +To learn more about the Lisk Interoperability and the current development status, check out [Lisk Improvement Proposal](https://github.com/LiskHQ/lips), [Research Forum](https://research.lisk.com/),
```suggestion
To learn more about the Lisk Interoperability and the current development status, check out [Lisk Improvement Proposal](https://github.com/LiskHQ/lips), [Research Forum](https://research.lisk.com/), [Lisk interoperability solution blog](https://lisk.com/blog/research/lisk-interoperability-solution-published) and [Lisk SDK v6.0.0 project board](https://github.com/orgs/LiskHQ/projects/10/views/4).
```

2022-02-23 08:37 UTC, mitsuaki-u requested changes
LGTM some minor changes

2022-02-23 08:37 UTC, mitsuaki-u commented on sdk/README.md
> +We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk
```suggestion
We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk.com/roadmap) which is summarized in the [Lisk interoperability solution blog.](https://lisk.com/blog/research/lisk-interoperability-solution-published) All related Lisk Improvement Proposals (LIPs) are published and currently being actively developed. It consists of 8 roadmap objectives.
```

2022-02-23 10:58 UTC, ishantiw commented on sdk/README.md
> +We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk
sapphire phase is not summarised in Lisk interoperability solution blog but it is part of sapphire phase. Adding the rest of the suggested code in separate commit

2022-02-23 11:12 UTC, shuse2 approved these changes

2022-02-23 13:35 UTC, mitsuaki-u commented on sdk/README.md
> +We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk
Ok the sentence just reads strange. How does a phase "bring a blog", not sure if it is grammatically or semantically correct.

2022-02-24 08:37 UTC, ishantiw commented on sdk/README.md
> +We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk
Like i said, the sentence is partially updated, please check the commit, there is no "blog"

2022-02-24 09:43 UTC, mitsuaki-u commented on sdk/README.md
> +We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk
I see that you fixed it now. Good work!

2022-02-24 09:45 UTC, mitsuaki-u commented on sdk/README.md
> +We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk
Actually it still reads strangely. Instead of the word "brings" I suggest "implements" or another word.

2022-02-24 10:00 UTC, mitsuaki-u approved these changes
One minor suggestion but approved from my end 👍

2022-02-24 11:20 UTC, ishantiw commented on sdk/README.md
> +We are currently working on [Sapphire phase](https://lisk.com/roadmap)[<img src="https://lisk.com/sites/default/files/2021-05/ico-sapphire.png" style="width:20px;vertical-align:middle">](https://lisk
since it is researched, designed and implemented, i thought it will be better to use "brings", I'll update it anyways

2022-02-24 15:50 UTC, merged