Fix order of bft execution - Closes #7060
LiskHQ/lisk-sdk pull request #7071
Opened 2022-03-14 11:26 UTC by shuse2

### What was the problem?

This PR resolves #7060 

### How was it solved?

- Update hook to be executed in `beforeTransactionsExecute`
- replace BFTValidator not exist error with continue. It is possible that generator address is not bft participant but valid generator of a block.

### How was it tested?
- Updated unit tests
- Run application more than 309 blocks from genesis

2022-03-14 18:10 UTC, janhack commented on framework/src/modules/bft/bft_votes.ts
> +			continue;
Same as above.

2022-03-14 18:11 UTC, janhack commented on framework/src/modules/bft/bft_votes.ts
> +				continue;
I updated my comment above.

2022-03-14 18:13 UTC, janhack requested changes
As commented, I think there is still a minor issues with respect to the computation of prevotes and precommits.

2022-03-16 14:18 UTC, mitsuaki-u approved these changes

2022-03-18 15:19 UTC, janhack reviewed
Note that we have the line
```
if (activeValidatorIndex > -1) {
```
This should always be `true` as otherwise `validatorInfo` before would not be defined. So the code is correct, but this additional if condition would not be necessary.

2022-03-18 15:19 UTC, janhack approved these changes

2022-03-22 13:52 UTC, merged