Implement sendInternal function for mainchain/sidechain stores - Closes #7040
LiskHQ/lisk-sdk pull request #7087
Opened 2022-03-29 07:21 UTC by ishantiw

### What was the problem?

This PR resolves #7040 

### How was it solved?

[🌱 Add schema](https://github.com/LiskHQ/lisk-sdk/commit/18aca1deeb4d16aed224ca42417690191d914e06)
  
[✅ Add get/set own account in baseInteroperabilityStore](https://github.com/LiskHQ/lisk-sdk/commit/e5280315d6537aecea78b4e497fe2a3f420b164a)
  
[🌱 Add mainchain sendInternal store function](https://github.com/LiskHQ/lisk-sdk/commit/7838a9bff0a878287f427a81ceb8c1fbd833450b)
  
[🌱 Add sendInternal fucntion for sidechain store](https://github.com/LiskHQ/lisk-sdk/commit/db3a713a0cba72b1ca2be64c9f4ef0063038b8bb)
  
[🌱 Add cross chain context testing utils](https://github.com/LiskHQ/lisk-sdk/commit/ce65096fc45f336087c1f47dbda26e80cd0c00f4)
  
[✅ Add mainchain sendInternal tests](https://github.com/LiskHQ/lisk-sdk/commit/c234563eb977cac7287d0175366facc6bd0a5898)
  
[✅ Add sidechain sendInternal unit tests](https://github.com/LiskHQ/lisk-sdk/commit/e38c31cc0e2a820973c67757a4370af8ca27dca7)

### How was it tested?

`npm run test:unit interoperability` under `framework`

2022-03-29 09:12 UTC, shuse2 requested changes

2022-03-30 08:46 UTC, mitsuaki-u reviewed
Some minor comments

2022-03-30 08:46 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/store.ts
> +				await mod.crossChainAPI?.beforeSendCCM(sendContext.beforeSendContext);
```suggestion
				await mod.crossChainAPI.beforeSendCCM(sendContext.beforeSendContext);
```

2022-03-30 08:46 UTC, mitsuaki-u commented on framework/src/modules/interoperability/sidechain/store.ts
> +		// Chain must be live; This check is always on the receivingChainID
Duplicate comment

2022-03-30 08:46 UTC, mitsuaki-u commented on framework/src/modules/interoperability/sidechain/store.ts
> +		// Chain must be live; This check is always on the receivingChainID
Duplicate comment

2022-03-30 08:46 UTC, mitsuaki-u commented on framework/src/modules/interoperability/sidechain/store.ts
> +				await mod.crossChainAPI?.beforeSendCCM(sendContext.beforeSendContext);
```suggestion
				await mod.crossChainAPI.beforeSendCCM(sendContext.beforeSendContext);
```

2022-03-30 08:46 UTC, mitsuaki-u commented on framework/src/modules/interoperability/sidechain/store.ts
> +				await mod.crossChainAPI?.beforeSendCCM(sendContext.beforeSendContext);
```suggestion
				await mod.crossChainAPI.beforeSendCCM(sendContext.beforeSendContext);
```

2022-03-30 12:27 UTC, mitsuaki-u approved these changes

2022-03-30 12:32 UTC, merged