Implement State Recovery Command for interoperability - Closes #7020 and #7021
LiskHQ/lisk-sdk pull request #7167
Opened 2022-05-13 07:38 UTC by mitsuaki-u

### What was the problem?

This PR resolves #7020 and #7021

### How was it solved?

- Implemented State Recovery verification hook 🌱 
- Implemented State Recovery execution hook 🌱 
- Added tests ✔️ 

### How was it tested?

Added unit tests

2022-05-16 12:13 UTC, Incede requested changes
Unit tests for `execute` seem to be missing and few minor comments.

2022-05-16 12:13 UTC, Incede commented on framework/src/modules/interoperability/schema.ts
> +export const stateRecoveryParams = {
`stateRecoveryParamsSchema`

2022-05-16 12:13 UTC, Incede commented on framework/src/modules/interoperability/schema.ts
> +	$id: '/modules/interoperability/mainchain/commands/state_recovery',
Prefer camelCase - `stateRecovery`

2022-05-16 14:04 UTC, ishantiw requested changes
Overall LGTM, couple of comments

2022-05-16 16:00 UTC, mitsuaki-u commented on framework/test/unit/modules/interoperability/mainchain/commands/state_recovery.spec.ts
> +			stateStore,
`createTransactionContext` was made specifically for testing purposes and should be fine to use in this test.

2022-05-17 13:54 UTC, mitsuaki-u commented on framework/test/unit/modules/interoperability/mainchain/commands/state_recovery.spec.ts
> +			stateStore,
As per discussion we have decided to use mock for this test as testing for sparseMerkleTree is already done extensively in the `lisk-tree` library

2022-05-18 12:40 UTC, ishantiw approved these changes
LGTM 🎉

2022-05-18 14:01 UTC, merged