Update reward module to emit an event - Closes #7287
LiskHQ/lisk-sdk pull request #7366
Opened 2022-08-04 12:02 UTC by sitetester

### What was the problem?

This PR resolves #7287

### How was it solved?

Reward module is updated to emit `rewardMinted` event with given constants.

### How was it tested?
test cases added in framework/test/unit/modules/reward/reward_module.spec.ts

2022-08-04 16:37 UTC, ishantiw requested changes

2022-08-04 16:37 UTC, ishantiw commented on framework/src/modules/reward/module.ts
> +		);
```suggestion
		const data = codec.encode(rewardMintedDataSchema, rewardMintedData);
		context.eventQueue.add(
			this.id,
			TYPE_ID_REWARD_MINTED,
			codec.encode(rewardMintedDataSchema, data),
			[context.header.generatorAddress],
		);
```

2022-08-04 16:37 UTC, ishantiw commented on framework/test/unit/modules/reward/reward_module.spec.ts
> +					BigInt(1) / BigInt(REWARD_REDUCTION_FACTOR_BFT),
why this?
```ts
					BigInt(1) / BigInt(REWARD_REDUCTION_FACTOR_BFT),
```

2022-08-04 16:37 UTC, ishantiw commented on framework/test/unit/modules/reward/reward_module.spec.ts
> +		it('should emit rewardMinted event for event type REWARD_REDUCTION_MAX_PREVOTES', async () => {
I think case for `REWARD_REDUCTION_FACTOR_BFT` is missing

2022-08-05 09:00 UTC, ishantiw approved these changes
Great job @sitetester 👏

2022-08-05 15:11 UTC, mitsuaki-u approved these changes
minor comment

2022-08-08 13:10 UTC, merged