Update interoperability sidechain registration - Closes #7440
LiskHQ/lisk-sdk pull request #7500
Opened 2022-09-07 15:13 UTC by mitsuaki-u

### What was the problem?

This PR resolves #7440 

### How was it solved?

- Updated schemas
- Added events
- Updated verify and execute logic

### How was it tested?

2022-09-12 20:29 UTC, mitsuaki-u commented on framework/src/modules/interoperability/constants.ts
>  export const THRESHOLD_MAINCHAIN = 68;
That is unrelated to this PR. Same for below comment

2022-09-12 20:32 UTC, mitsuaki-u commented on framework/src/modules/interoperability/events/ccm_processed.ts
> +		ctx: EventQueuer,
I am following the convention in the `BaseEvent` class, which uses the name `ctx`. I will keep it and you can create another issue to change it as it is unrelated to this PR.

2022-09-12 20:34 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/commands/sidechain_registration.ts
> +					`Invalid name property. It should contain only characters from the set [a-z0-9!@$&_.].`,
The error message comes from the LIP PR: https://github.com/LiskHQ/lips/pull/148. I will keep it as is.

2022-09-12 20:34 UTC, mitsuaki-u commented on framework/src/modules/interoperability/constants.ts
>  export const CHAIN_REGISTERED = 0;
These constants are specified in the LIP: https://github.com/LiskHQ/lips/pull/148. I will keep it as is.

2022-09-12 20:34 UTC, mitsuaki-u commented on framework/src/modules/interoperability/constants.ts
>  export const MIN_RETURN_FEE = BigInt(1000);
Unrelated to this PR

2022-09-13 11:37 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/commands/sidechain_registration.ts
> +		// Emit chain account updated event.
I am following the convention in the BaseEvent class. Events are added to the queue and then emitted.

2022-09-13 11:37 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/module.ts
> +			this.interoperableCCAPIs,
As discussed, we will follow what is in the feature branch until it is updated, not development branch.

2022-09-13 11:43 UTC, mitsuaki-u commented
@sitetester @ishantiw As discussed and agreed upon in our meeting and noting here:  1. Comments unrelated to the code changed in the PR or unrelated to the PR issue should be addressed in a separately. 2. Constant names will be kept as stated in LIP: https://github.com/LiskHQ/lips/pull/148 (but error messages can be updated).  I will indicate with a "👎" and resolve above related comments and address the rest.

2022-09-13 11:57 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/commands/sidechain_registration.ts
> +					`Invalid name property. It should contain only characters from the set [a-z0-9!@$&_.].`,
I will leave as is as it is easier to see immediately which characters are allowed or not this way.

2022-09-13 11:59 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/commands/sidechain_registration.ts
> +		const chainDataExists = await chainDataSubstore.has(context, chainID);
IMO `chainDataExists` is more clear and easier to read

2022-09-13 16:03 UTC, Incede requested changes

2022-09-13 16:03 UTC, Incede commented on framework/src/modules/interoperability/constants.ts
>  export const COMMAND_NAME_SIDECHAIN_REG = 'sidechainRegistration';
```suggestion
export const COMMAND_SIDECHAIN_REG = 'sidechainRegistration';
```

2022-09-14 14:48 UTC, ishantiw commented on framework/src/modules/interoperability/constants.ts
> +export const TOKEN_ID_LSK = Buffer.from([0, 0, 0, 1, 0, 0, 0, 0]);
I think it should be `000000000000` after chainID but maybe we should wait for Token LIP update on this one. Please make a comment as `TODO: To be updated after token module update `

2022-09-15 18:38 UTC, shuse2 commented on framework/src/modules/interoperability/mainchain/commands/sidechain_registration.ts
> +		// Emit chain account updated event.
I think @sitetester means comment and the function name is not matching?

2022-09-16 07:02 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/commands/sidechain_registration.ts
> +		// Emit chain account updated event.
I think comment is clear and conveys that an event will be emitted. Also the comment comes from the LIP. Will keep as is if it's ok.

2022-09-16 07:32 UTC, mitsuaki-u commented on framework/src/modules/interoperability/events/ccm_processed.ts
> +		ccmID: Buffer,
Yes according to the LIP it should be included

2022-09-16 07:48 UTC, shuse2 commented on framework/src/modules/interoperability/events/ccm_processed.ts
> +		ccmID: Buffer,
yes, but i meant here
```
public log(
		ctx: EventQueuer,
		sendingChainID: Buffer,
		receivingChainID: Buffer,
//		ccmID: Buffer,  <= this ccmID can be taken from data
		data: CcmProcessedEventData,
	): void {
```

2022-09-19 13:11 UTC, ishantiw requested changes
Overall LGTM, couple of minor comments

2022-09-19 13:11 UTC, ishantiw commented on framework/src/modules/interoperability/stores/chain_account.ts
> +	required: ['name', 'lastCertificate', 'status'],
update the fieldNumber for 'lastCertificate', 'status'

2022-09-19 14:04 UTC, ishantiw approved these changes
🚀

2022-09-19 14:19 UTC, shuse2 requested changes

2022-09-19 14:19 UTC, shuse2 commented on framework/test/unit/modules/interoperability/mainchain/commands/sidechain_registration.spec.ts
> +		it('should return error if store key chainID already exists in chainID store', async () => {
i think cases for 
* ` trs.params.chainID[0] != CHAIN_ID_MAINCHAIN[0]:`
* sidechainRegistrationFee !== REGISTRATION_FEE
* vailableBalance < REGISTRATION_FEE
are missing?

2022-09-19 14:19 UTC, shuse2 commented on framework/test/unit/modules/interoperability/mainchain/commands/sidechain_registration.spec.ts
> +			expect(chainAccountUpdatedEvent.log).toHaveBeenCalled();
these should also check the input as well? same as other event expectations

2022-09-20 07:38 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/commands/sidechain_registration.ts
> +			messageFeeTokenID,
`TOKEN_ID_LSK` has a different type from what is required in `messageFeeTokenID`

2022-09-20 07:40 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/commands/sidechain_registration.ts
> +			sendingChainID: ownChainAccount.id,
no `id` is correct

2022-09-20 07:41 UTC, mitsuaki-u commented on framework/src/modules/interoperability/base_interoperability_store.ts
> +				const chainIDBuffer = utils.intToBuffer(chainAccount.key.readUInt32BE(0), 4);
This code is from a different PR. I merely updated the variable names to be more clear but I can update it if the code in the previous PR was invalid.

2022-09-20 13:29 UTC, shuse2 approved these changes
🚀

2022-09-20 16:46 UTC, merged