Expose state_prove RPC to generate multiproof - CLoses #7467
LiskHQ/lisk-sdk pull request #7509
Opened 2022-09-08 08:55 UTC by Incede

### What was the problem?

This PR resolves #7467

### How was it solved?

- Implement as specified
- Fix bug in `abi_handler.ts`

### How was it tested?

Added unit tests

2022-09-08 09:04 UTC, shuse2 requested changes

2022-09-08 09:16 UTC, Incede commented on framework/src/engine/endpoint/state.ts
> +		validator.validate(stateProveRequestSchema, ctx.params);
same could be done [here](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/engine/endpoint/chain.ts#L203) and multiple other places.

2022-09-08 12:07 UTC, shuse2 commented on framework/src/engine/endpoint/state.ts
> +			stateRoot: ctx.params.stateRoot,
ah sorry, i missed it on the first review. We cannot prove the past state root, so I think `stateRoot` should come from last block header

2022-09-08 14:55 UTC, shuse2 approved these changes

2022-09-12 07:45 UTC, ishantiw approved these changes

2022-09-12 07:46 UTC, merged