Define storage for saving info about legacy chain brackets - Closes #7545
LiskHQ/lisk-sdk pull request #7581
Opened 2022-09-27 12:14 UTC by mosmartin

### What was the problem?

This PR resolves #7545

### How was it solved?

- Update codecs
- Update the legacy schema
- Add getLegacyChainBracketInfo() method
- Add setLegacyChainBracketInfo() method

### How was it tested?

Added unit tests

2022-09-27 15:57 UTC, ishantiw requested changes
LGTM, one comment

2022-09-27 15:57 UTC, ishantiw commented on framework/src/engine/legacy/legacy_chain_handler.ts
> +			if (!bracket.snapshotBlockID) {
you also need to check `storage.getLegacyChainBracketInfo(bracket.snapshotBlockID)` exists or not, we only specify defaults when it doesn't exist in DB

2022-09-27 15:57 UTC, ishantiw commented on framework/src/engine/legacy/schemas.ts
> +	$id: '/lisk/legacyChainBracketInfo',
Maybe?
```suggestion
	$id: '/legacy/legacyChainBracketInfo',
```

2022-09-28 14:34 UTC, ishantiw approved these changes
Well done 👏

2022-10-05 18:53 UTC, mosmartin commented on framework/test/unit/engine/legacy/storage.spec.ts
> +	describe('getLegacyChainBracketInfo', () => {
In my opinion it's self explanatory, no need for comments.

2022-10-05 19:07 UTC, mosmartin commented on framework/test/unit/engine/legacy/storage.spec.ts
> +			expect(result).toEqual(encodeLegacyChainBracketInfo(bracketInfo));
For readability!

2022-10-06 07:52 UTC, merged