Fix core crash - Closes #7368, #7447 and #7591
LiskHQ/lisk-sdk pull request #7602
Opened 2022-10-03 09:02 UTC by shuse2

### What was the problem?

This PR resolves #7368 , resolves #7447 and resolves #7591

1. In case of application success to commit but engine fails, it leaves the data at inconsistent state
2. If genesis state execution takes too long, it leaves the data at inconsistent state
3. ABI request was not counting the ID, so if there are multiple calls at the same time, req/res will be mixed
4. `oclif-dev` command was outdated

### How was it solved?

- Update ABI call from `ready` to `init` and add state revert logic in case of inconsistent state
- Update `oclif-dev` to use `oclif` command
- Update ABI client to count the ID

### How was it tested?

- Run lisk-core and lisk-service together
or
- Run dpos-mainchain and make multiple RPC request and see it doesnt crash

2022-10-03 18:48 UTC, shuse2 commented on commander/package.json
> +		"prepack": "oclif manifest"
this only executed in publication, so testing this fails without this =)

2022-10-03 20:45 UTC, ishantiw requested changes

2022-10-03 20:45 UTC, ishantiw commented on framework/src/abi_handler/abi_handler.ts
> +		// Slip if state db is already initialized
```suggestion
		// Skip if state db is already initialized
```

2022-10-03 20:45 UTC, ishantiw commented on framework/src/abi_handler/abi_handler.ts
> +				'Skip caching genesis state. state is already initialized',
```suggestion
				'Skip caching genesis state as it is already initialized',
```

2022-10-03 20:45 UTC, ishantiw commented on framework/src/abi_handler/abi_handler.ts
> +				`Invalid engine state. Conflict at height Engine: ${req.lastBlockHeight} and application state ${currentState.version}.`,
Shouldn't this be?
```suggestion
				`Invalid engine state. Conflict at engine height: ${req.lastBlockHeight} and application state ${currentState.version}.`,
```

2022-10-03 20:45 UTC, ishantiw commented on framework/src/abi_handler/abi_handler.ts
> +		// eslint-disable-next-line
Can we be specific what is disabled on the next line?

2022-10-03 20:45 UTC, ishantiw commented on framework/src/abi_handler/abi_client.ts
> +			'Reseived response from ABI server',
```suggestion
			'Received response from ABI server',
```

2022-10-03 20:59 UTC, ishantiw approved these changes
🎉

2022-10-04 13:44 UTC, shuse2 commented on framework/test/unit/abi_handler/abi_handler.spec.ts
> +					lastStateRoot: utils.getRandomBytes(32),
yes that is on purpose to test if it doesn't match, same for below

2022-10-04 14:58 UTC, merged