Update crosschain transfer command - Closes #7574
LiskHQ/lisk-sdk pull request #7637
Opened 2022-10-13 10:04 UTC by has5aan

### What was the problem?

This PR resolves #7574 

### How was it solved?

Updated Cross chain transfer command.

### How was it tested?

WIP

2022-10-13 20:07 UTC, shuse2 reviewed
Overall it looks good!

2022-10-13 20:07 UTC, shuse2 commented on framework/src/modules/token/schemas.ts
> +		escrowInitializationFee: {
you can use `feeTokenID` for this (ie: it should be the same tokenID)

2022-10-13 20:07 UTC, shuse2 commented on framework/src/modules/token/commands/cc_transfer.ts
> +	MODULE_NAME_TOKEN,
It is better to pass the module name from module through init or constructor because name is dynamically generated by class name

2022-10-13 20:07 UTC, shuse2 commented on framework/src/state_machine/types.ts
> +	getMethodContext: () => MethodContext;
this should be `ImmutableMethodContext` because it cannot use `set` in verify context

2022-10-17 13:51 UTC, shuse2 requested changes
Overall looks good! some minor points

2022-10-17 13:51 UTC, shuse2 commented on framework/src/modules/token/commands/cc_transfer.ts
> +				![this._ownChainID, params.receivingChainID, MAINCHAIN_ID].some(allowedChainID =>
`MAINCHAIN_ID` should be computed using `[mainchainID]] = splitTokenID(this._tokenMethod.getMainchainTokenID())`

2022-10-17 13:51 UTC, shuse2 commented on framework/src/modules/token/constants.ts
> +export const MODULE_NAME_TOKEN = 'token';
this can be removed

2022-10-17 13:51 UTC, shuse2 commented on framework/src/modules/token/constants.ts
> +export const MAINCHAIN_ID = Buffer.from([0, 0, 0, 0]);
this can be removed with above change

2022-10-17 13:51 UTC, shuse2 commented on framework/test/unit/modules/token/commands/cc_transfer.spec.ts
> + * Copyright © 2020 Lisk Foundation
```suggestion
 * Copyright © 2022 Lisk Foundation
```

2022-10-17 13:51 UTC, shuse2 commented on framework/test/unit/modules/token/commands/cc_transfer.spec.ts
> +	beforeAll(() => {
`beforeEach` would be better here to ensure atomicity on each test

2022-10-18 08:44 UTC, shuse2 approved these changes

2022-10-19 09:45 UTC, Incede approved these changes

2022-10-19 09:49 UTC, merged