Update Channel Terminated Message cross chain command - Closes #7656
LiskHQ/lisk-sdk pull request #7696
Opened 2022-10-26 11:23 UTC by Phanco

### What was the problem?

This PR resolves #INSERT_ISSUE_NUMBER

### How was it solved?

### How was it tested?

2022-10-28 10:36 UTC, ishantiw requested changes
maybe its better to rename, `base_classes` or `common` to be more precise and also move other base classes within it that are present within `interoperability` folder?

2022-10-28 10:36 UTC, ishantiw commented on framework/src/modules/interoperability/base/cc_commands/channel_terminated.ts
> +			);
This logic is removed from the recent update, please refer to https://github.com/LiskHQ/lips/blob/main/proposals/lip-0049.md#channel-terminated-message-1, I have also updated the issue

2022-10-28 10:36 UTC, ishantiw commented on framework/src/modules/interoperability/schemas.ts
>  };
now we have an empty schema

2022-10-28 10:40 UTC, Phanco commented
> maybe its better to rename, `base_classes` or `common` to be more precise and also move other base classes within it that are present within `interoperability` folder?

Since those classes starts with `Base` so I would go probably for `base_classes`

2022-10-28 11:29 UTC, Phanco commented
@ishantiw that involves quite a number of file changes if I move `base_*` files to `base_classes` folder. Is it okay if I do it in another PR?
<img width="625" alt="image" src="https://user-images.githubusercontent.com/11695608/198576849-0ddf6186-ec18-465e-bbd5-71f27fc3390e.png">

2022-10-28 11:34 UTC, ishantiw commented
lets refactor this later in another issue,
https://github.com/LiskHQ/lisk-sdk/pull/7696#issuecomment-1294882751

Meanwhile use `base_cc_commands` folder instead of just `base` and later we can rename it to `base_classes` and move everything else.

2022-11-01 10:30 UTC, ishantiw reviewed
@Phanco lgtm, maybe we can move test to one common file as @sitetester suggests. You can follow similar approach as we have in https://github.com/LiskHQ/lisk-sdk/pull/7700

2022-11-02 10:13 UTC, Phanco commented
> @Phanco lgtm, maybe we can move test to one common file as @sitetester suggests. You can follow similar approach as we have in #7700

Took reference on #7700 and updated test case, thanks :D

2022-11-04 10:33 UTC, Phanco commented on framework/src/modules/interoperability/sidechain/cc_commands/channel_terminated.ts
> +export class SidechainCCChannelTerminatedCommand extends BaseCCChannelTerminatedCommand {
I saw quite a few `getInteroperabilityInternalMethod` are using `context: StoreGetter | ImmutableStoreGetter`. 

Yeah I think need some inspiration from @ishantiw

2022-11-04 10:34 UTC, Phanco commented on framework/test/unit/modules/interoperability/base_cc_commands/channel_terminated.spec.ts
> +	mainchainInteroperabilityInternalMethod.isLive = jest.fn().mockResolvedValue(false);
Done :D

2022-11-07 11:05 UTC, ishantiw commented on framework/src/modules/interoperability/sidechain/cc_commands/channel_terminated.ts
> +export class SidechainCCChannelTerminatedCommand extends BaseCCChannelTerminatedCommand {
basically we want to remove `ImmutableStoreGetter` in future and use `context: StoreGetter | ImmutableStoreGetter` but lets tackle it later when we have more clear picture. I think we should think about i and do it after https://github.com/LiskHQ/lisk-sdk/issues/7719

2022-11-07 11:07 UTC, ishantiw approved these changes

2022-11-07 15:40 UTC, merged