Update message recovery command
LiskHQ/lisk-sdk pull request #7782
Opened 2022-11-15 18:27 UTC by sitetester

### What was the problem?

This PR resolves #7727

### How was it solved?

Common code moved to BaseMessageRecoveryCommand

### How was it tested?
- test cases moved to single file & further duplication issues addressed
- still work In progress...

2022-11-22 14:18 UTC, ishantiw requested changes
We need to remove message recovery from sidechain and associated code.

2022-11-22 14:18 UTC, ishantiw commented on framework/src/modules/interoperability/mainchain/commands/message_recovery.ts
> +		return verifyMessageRecovery(context.params, terminatedChainOutboxAccount);
I don't feel that having this function is much helping us as we only have this code in this verify function and also we are looping twice over the deserialized CCMs just for isLive function. Maybe move all the logic to this place as we are not using it in sidehchain module.

2022-11-22 14:18 UTC, ishantiw commented on framework/src/modules/interoperability/mainchain/commands/message_recovery.ts
> +		// const crossChainMessages = params.crossChainMessages.map(ccmBytes => codec.decode<CCM>(ccmSchema, ccmBytes))
we can remove this

2022-11-22 14:18 UTC, ishantiw commented on framework/src/modules/interoperability/mainchain/commands/message_recovery.ts
> +		if (!terminatedOutboxAccount) {
we don't need this check as its already checked in verify

2022-11-22 14:18 UTC, ishantiw commented on framework/src/modules/interoperability/mainchain/commands/message_recovery.ts
> +		terminatedOutboxAccount.outboxRoot = regularMerkleTree.calculateRootFromUpdateData(
you also need to set this value back in the TerminatedOutboxStore store

2022-11-22 16:19 UTC, ishantiw approved these changes
Overall looks fine to me, few more comments

2022-11-22 16:19 UTC, ishantiw commented on framework/src/modules/interoperability/mainchain/commands/message_recovery.ts
> +		if (!terminatedOutboxAccount) {
you can move this condition inside catch above, 

```ts
catch (error) {
		if (error instanceof NotFoundError)) {
			return {
				status: VerifyStatus.FAIL,
				error: new Error('Terminated outbox account does not exist.'),
			};
		}
		throw error
	}
```

2022-11-22 16:19 UTC, ishantiw commented on framework/test/unit/modules/interoperability/mainchain/commands/message_recovery.spec.ts
> +		it('should proceed without error if the sending chain is the mainchain', async () => {
should call applyRecovery ? and also check applyRecovery to have been called with right params?

2022-11-22 16:19 UTC, ishantiw commented on framework/test/unit/modules/interoperability/mainchain/commands/message_recovery.spec.ts
> +		it('should proceed without error if the sending chain is not the mainchain', async () => {
same as above, 
should call forwardRecovery ? and also check forwardRecovery to have been called with right params?

2022-11-22 16:19 UTC, ishantiw commented on framework/test/unit/modules/interoperability/mainchain/commands/message_recovery.spec.ts
> +		it('should proceed without error if the sending chain is not the mainchain', async () => {
also check that terminatedOutboxAccount.set is called or it has been set if in memory calling `.has`? same below

2022-11-22 16:20 UTC, ishantiw requested changes
Updating to review changes

2022-11-23 14:57 UTC, mitsuaki-u approved these changes
Well documented comments :)

2022-11-23 15:07 UTC, ishantiw requested changes
Just one more comment and it should be good

2022-11-23 15:07 UTC, ishantiw commented on framework/src/modules/interoperability/mainchain/commands/message_recovery.ts
> +		const deserializedCCMs = crossChainMessages.map(serializedCcm =>
we can move decoding part within the loop below

2022-11-23 15:24 UTC, ishantiw approved these changes
🎉

2022-11-24 00:46 UTC, merged