Implement liveness terminate command
LiskHQ/lisk-sdk pull request #7797
Opened 2022-11-17 16:45 UTC by ishantiw

### What was the problem?

This PR resolves #7766 

### How was it solved?

[🌱](https://github.com/LiskHQ/lisk-sdk/commit/293e3cbba98f5c4df13a62b5e1b4f5a7f5edb906) [Implement liveness terminate command](https://github.com/LiskHQ/lisk-sdk/commit/293e3cbba98f5c4df13a62b5e1b4f5a7f5edb906) https://github.com/LiskHQ/lisk-sdk/issues/7766 

- Add params schema
- Implement verify and execute functions
- Add interface
- Add command name constant
- Add unit tests

### How was it tested?

`npm run test:unit terminate_sidechain`

2022-11-17 17:04 UTC, shuse2 requested changes

2022-11-17 17:04 UTC, shuse2 commented on framework/src/modules/interoperability/mainchain/commands/terminate_sidechain_for_liveness.ts
> +		}
without this, the below `get` will throw if not found, it should work the same

2022-11-17 17:04 UTC, shuse2 commented on framework/test/unit/modules/interoperability/mainchain/commands/terminate_sidechain_for_liveness.spec.ts
> +			await livenessTerminationCommand.execute(commandExecuteContext);
it's good to expect the `terminateChainInternal` is called with expected chainID?

2022-11-17 17:39 UTC, shuse2 approved these changes

2022-11-22 12:16 UTC, mitsuaki-u approved these changes

2022-11-22 14:02 UTC, merged