Update state recovery command
LiskHQ/lisk-sdk pull request #7805
Opened 2022-11-21 14:42 UTC by mitsuaki-u

### What was the problem?

This PR resolves #7726 

### How was it solved?

- Updated state recovery on mainchain logic

### How was it tested?

- Updated unit tests

2022-11-21 16:25 UTC, ishantiw requested changes
I think some test cases are missing as follows,
- `Interoperability module cannot be recovered`
- `Module is not registered on the chain`
- `Module is not recoverable`
- `Recovered store value cannot be empty`

2022-11-21 16:25 UTC, ishantiw commented on framework/src/modules/interoperability/mainchain/commands/state_recovery.ts
> +				error: new Error('The terminated account does not exist.'),
```suggestion
				error: new Error('The terminated state account does not exist.'),
```

2022-11-21 17:30 UTC, mitsuaki-u commented on framework/src/modules/interoperability/mainchain/commands/state_recovery.ts
>  			});
Updated error message but what does it have to do with the quoted line 109?

2022-11-21 17:31 UTC, mitsuaki-u commented on framework/src/modules/interoperability/types.ts
> +export interface RecoverContext {
It's not really return type as there is nothing returned from `recover` function

2022-11-22 09:32 UTC, ishantiw commented on framework/src/modules/interoperability/mainchain/commands/state_recovery.ts
>  			});
ah I couldn't add message at Line 126, thats why. but yeah just wanted to get error messages updated

2022-11-22 09:35 UTC, ishantiw commented on framework/src/modules/interoperability/types.ts
> +export interface RecoverContext {
then you have to update Line 143 where you typecasted it as `recover: () => RecoverContext;`, I think it should be `recover: (ctx: RecoverContext) => Promise<void>;`

2022-11-22 11:43 UTC, Phanco approved these changes

2022-11-22 11:46 UTC, merged