Collect CCMs from the events for Chain connector plugin
LiskHQ/lisk-sdk pull request #7838
Opened 2022-11-30 12:08 UTC by sitetester

### What was the problem?

This PR resolves #7378

### How was it solved?

Plugin updated per requirements

### How was it tested?

Test cases added

2022-12-06 13:23 UTC, shuse2 requested changes

2022-12-06 13:23 UTC, shuse2 commented on framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts
> +				async (data?: Record<string, unknown>) => this._newBlockHandler(data),
Maybe it's outside of the PR, but it's not necessary to listen to the `network_newBlock` event. All the executed block will be emitted through `chain_newBlock` event

2022-12-06 13:23 UTC, shuse2 commented on framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts
> +		// noinspection TypeScriptValidateJSTypes
do we need this comment? if so, it would be better to be rephrased

2022-12-06 13:23 UTC, shuse2 commented on framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts
> +					eventAttr.module === MODULE_NAME_INTEROPERABILITY,
```suggestion
					eventAttr.name === 'ccmSendSuccess' &&
					eventAttr.module === MODULE_NAME_INTEROPERABILITY,
```
Also, maybe it's probably better to make it as a constant

2022-12-06 13:23 UTC, shuse2 commented on framework-plugins/lisk-framework-chain-connector-plugin/test/unit/plugin.spec.ts
> +			expect((chainConnectorPlugin as any)['_cleanup']).toHaveBeenCalled();
why cleanup will be called on the `_newBlockHeader` handler?

2022-12-06 16:12 UTC, shuse2 approved these changes

2022-12-06 16:12 UTC, shuse2 commented on framework-plugins/lisk-framework-chain-connector-plugin/test/unit/plugin.spec.ts
> +const getApiClientMocks = () => {
instead of creating function, you can just use 

`let apiClient;`
and in `beforeEach`, reassign the mocks

2022-12-08 16:21 UTC, shuse2 requested changes

2022-12-08 16:21 UTC, shuse2 commented on framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts
> +			this._chainConnectorState.crossChainMessages = ccmSendSuccessEvents.map(e => ({
here we shouldn't overwrite the value

2022-12-13 14:09 UTC, ishantiw commented on framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts
> +		if (events) {
events can be empty array, so `events.length > 0`?

2022-12-13 14:09 UTC, ishantiw commented on framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts
> +					ccm: codec.decode<CCMsg>(ccmSchema, Buffer.from(e.data, 'hex')),
I think here we can use `setCrossChainMessages` db to store ccms

2022-12-13 14:09 UTC, ishantiw commented on framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts
> +			this._chainConnectorState.crossChainMessages.filter(
I think filter returns the filtered array so you need to update the original array

2022-12-13 14:09 UTC, ishantiw commented on framework-plugins/lisk-framework-chain-connector-plugin/src/types.ts
> +
maybe we can remove it as we have a db store for ccms to be retrieved or set by height

2022-12-13 14:19 UTC, Phanco commented on framework-plugins/lisk-framework-chain-connector-plugin/src/constants.ts
> +export const CCM_SEND_SUCCESS = `ccmSendSuccess`;
can use `''` instead

2022-12-16 14:03 UTC, ishantiw approved these changes

2022-12-16 14:04 UTC, merged