Add `punishmentPeriod` property to all PoS endpoints that return validator account
LiskHQ/lisk-sdk pull request #7854
Opened 2022-12-02 11:57 UTC by bobanm

### What was the problem?

This PR resolves #7807

### How was it solved?

- Introduced `punishmentPeriod` property with start and end punishment block heights to all 3 PoS endpoints that return validator account: `pos_getValidator`, `pos_getAllValidators` and `pos_getValidatorsByStake`
- Introduced `ValidatorAccountEndpoint` to simplify the return type.

### How was it tested?

Added `punishmentPeriod` property to all the unit tests which test those 3 endpoints.

2022-12-02 13:39 UTC, shuse2 requested changes
I think response schema changes are missing

2022-12-02 13:39 UTC, shuse2 commented on framework/src/modules/pos/endpoint.ts
> +	private _calculatePunishmentPeriods(pomHeights: number[], period = PUNISHMENT_PERIOD) {
I think second params is never used, so it's ok to just use the constant in the function

2022-12-05 18:16 UTC, shuse2 approved these changes

2022-12-05 19:06 UTC, has5aan approved these changes

2022-12-05 20:58 UTC, merged