Add missing check in sidechain cross chain command execution
LiskHQ/lisk-sdk pull request #7915
Opened 2022-12-27 14:45 UTC by sitetester

### What was the problem?

This PR resolves #7907

### How was it solved?

Missing check applied

### How was it tested?
Corresponding test cased added

2023-01-02 14:06 UTC, shuse2 requested changes

2023-01-02 14:06 UTC, shuse2 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +				if (context.chainID !== ccm.receivingChainID) {
```suggestion
				if (!context.chainID.equals(ccm.receivingChainID)) {
```

2023-01-02 21:40 UTC, ishantiw commented on framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts
> +		it('should reject terminate the chain and add an event when CCM is not directed to the sidechain', async () => {
this test case description sounds confusing `should reject terminate the chain`

2023-01-03 09:28 UTC, ishantiw approved these changes

2023-01-09 14:22 UTC, shuse2 requested changes

2023-01-12 14:44 UTC, shuse2 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +				if (isMainchain && !ccm.sendingChainID.equals(params.sendingChainID)) {
I think this should be the case regardless of the chain?

2023-01-12 14:44 UTC, shuse2 commented on framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts
> +				expect.toBeArrayOfSize(1),
why is it different now?

2023-01-12 14:44 UTC, shuse2 commented on framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts
> +					receivingChainID: chainID,
that's only for the sidechain, but it was resolved

2023-01-12 16:44 UTC, shuse2 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +				if (isMainchain && !ccm.sendingChainID.equals(params.sendingChainID)) {
ah that's true. then all good

2023-01-12 16:53 UTC, shuse2 commented on framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts
> +				expect.toBeArrayOfSize(1),
ah because you removed the `...params.inboxUpdate.crossChainMessages`

2023-01-12 16:53 UTC, shuse2 approved these changes

2023-01-13 11:35 UTC, merged