commandExecutionResult event should be logged after afterCommandExecute hook
LiskHQ/lisk-sdk pull request #7991
Opened 2023-01-11 18:31 UTC by Incede

### What was the problem?

This PR resolves #7944 

### How was it solved?

Change order of events

### How was it tested?

Update unit test

2023-01-12 13:09 UTC, shuse2 commented on framework/src/state_machine/state_machine.ts
> +					ctx.eventQueue.unsafeAdd(
standard event should be added based on the result of the execution.
if transaction is invalid, the event should not be added

2023-01-13 09:51 UTC, mosmartin commented
Hi @Incede, this is not part of the PR (and you don't have to impl it 🙂 just FYI) but I noticed the import section of `framework/test/unit/state_machine/custom_modules.ts` could be cleaned up 
```typescript
import { BaseMethod, BaseCommand, BaseEndpoint, BaseModule } from '../../../src';
import { TransactionVerifyResult } from '../../../src/abi';
import { ModuleMetadata } from '../../../src/modules/base_module';
import {
	BlockAfterExecuteContext,
	BlockExecuteContext,
	GenesisBlockExecuteContext,
	TransactionExecuteContext,
} from '../../../src/state_machine';
```
to
```typescript
import {
	BaseMethod,
	BaseCommand,
	BaseEndpoint,
	BaseModule,
	TransactionVerifyResult,
	ModuleMetadata,
	BlockAfterExecuteContext,
	BlockExecuteContext,
	GenesisBlockExecuteContext,
	TransactionExecuteContext,
} from '../../../src';
```
since all the exports have been aggregated in the index file at `../../../src`

2023-01-13 10:35 UTC, Incede commented
> Hi @Incede, this is not part of the PR (and you don't have to impl it 🙂 just FYI) but I noticed the import section of `framework/test/unit/state_machine/custom_modules.ts` could be cleaned up
> 
> ```ts
> import { BaseMethod, BaseCommand, BaseEndpoint, BaseModule } from '../../../src';
> import { TransactionVerifyResult } from '../../../src/abi';
> import { ModuleMetadata } from '../../../src/modules/base_module';
> import {
> 	BlockAfterExecuteContext,
> 	BlockExecuteContext,
> 	GenesisBlockExecuteContext,
> 	TransactionExecuteContext,
> } from '../../../src/state_machine';
> ```
> 
> to
> 
> ```ts
> import {
> 	BaseMethod,
> 	BaseCommand,
> 	BaseEndpoint,
> 	BaseModule,
> 	TransactionVerifyResult,
> 	ModuleMetadata,
> 	BlockAfterExecuteContext,
> 	BlockExecuteContext,
> 	GenesisBlockExecuteContext,
> 	TransactionExecuteContext,
> } from '../../../src';
> ```
> 
> since all the exports have been aggregated in the index file at `../../../src`
> 
> Also, since this is a unit test file, maybe you could update the filename to follow the conventon `*.spec.ts?` 🙂

Cleaned up the imports. Kept the file name unchanged as discussed.

2023-01-13 10:47 UTC, shuse2 requested changes

2023-01-13 10:47 UTC, shuse2 commented on framework/src/state_machine/state_machine.ts
> +
```suggestion
		ctx.eventQueue.unsafeAdd(
			ctx.transaction.module,
			EVENT_TRANSACTION_NAME,
			codec.encode(standardEventDataSchema, { success: status ===  TransactionExecutionResult.OK }),
			[ctx.transaction.id],
		);
```

2023-01-13 11:10 UTC, shuse2 approved these changes

2023-01-13 11:27 UTC, mosmartin approved these changes

2023-01-13 11:57 UTC, merged