txpool_getTransactionsFromPool endpoint to return JSON
LiskHQ/lisk-sdk pull request #7995
Opened 2023-01-12 13:36 UTC by has5aan

### What was the problem?

This PR resolves #7956 

### How was it solved?

Modified `framework/src/engine/endpoint/txpool.ts` to return `JSONObject<TransactionObject>`.

### How was it tested?
Implemented unit tests.

2023-01-12 14:12 UTC, shuse2 requested changes

2023-01-12 14:12 UTC, shuse2 commented on framework/src/engine/endpoint/txpool.ts
> +		return this._pool.getAll().map(transaction => ({
I think we can simply return `TransactionJSON[]` here, and you can just switch to `tx.getJSON()`

2023-01-12 14:47 UTC, shuse2 commented on framework/src/engine/endpoint/txpool.ts
> +		return this._pool.getAll().map(transaction => ({
ah yes...
we can for now dow `(this._pool.getAll() as Transaction[]).map(tx => tx.toJSON())` or add `toJSON` in the interface in the pool

2023-01-12 20:59 UTC, shuse2 approved these changes

2023-01-13 07:49 UTC, Incede approved these changes

2023-01-13 07:51 UTC, merged