Update MainchainCrossChainUpdate command execute function based on LIP0053 update
LiskHQ/lisk-sdk pull request #8030
Opened 2023-01-17 16:30 UTC by sitetester

### What was the problem?

This PR resolves #8017

### How was it solved?
Mainly base_cross_chain_update_command.ts::executeCommon part is updated

### How was it tested?

2023-01-22 18:20 UTC, ishantiw requested changes

2023-01-22 18:20 UTC, ishantiw commented on framework/src/modules/interoperability/types.ts
> +
- Add LIP reference https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#empty-cross-chain-message
- Order the properties as per `ccmSchema` and the [LIP: EMPTY_CCM](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#empty-cross-chain-message)

2023-01-22 18:20 UTC, ishantiw commented on framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts
> +		// decoding
I think we can remove this comment, either we can encapsulate tests within describe with topic or `it('...')` description are good enough?

2023-01-22 18:20 UTC, ishantiw commented on framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts
> +		// format
same here

2023-01-22 18:20 UTC, ishantiw commented on framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts
> +		it('should update validators if activeValidatorsUpdate is not empty', async () => {
I think there should be separate test cases to cover, 
`if len(ccu.params.certificate) > 0 updateCertificate(ccu)`
`if ccu.params.inboxUpdate is not empty and len(ccu.params.certificate) > 0: updatePartnerChainOutboxRoot(ccu)`

2023-01-23 08:16 UTC, shuse2 requested changes

2023-01-23 08:16 UTC, shuse2 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +			bftWeightsUpdateBitmap !== EMPTY_BYTES ||
original condition is correct, and buffer cannot be compared with `!==`

2023-01-23 08:16 UTC, shuse2 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +		const validators = await chainValidatorsStore.get(context, params.sendingChainID);
Minor point, but no need to split the declaration here?

2023-01-23 08:16 UTC, shuse2 commented on framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts
> +		// The CCM must come from the sending chain.
same as above @ishantiw 's comment

2023-01-23 08:16 UTC, shuse2 commented on framework/test/unit/modules/interoperability/base_cross_chain_update_command.spec.ts
> +		// The CCM must come be directed to the sidechain, unless it was bounced on the mainchain.
same as above @ishantiw 's comment

2023-01-23 12:13 UTC, shuse2 approved these changes

2023-01-23 13:53 UTC, ishantiw approved these changes
Looks good, couple of minor comments related to TypeDoc but we can keep in mind for future PRs

2023-01-23 13:53 UTC, ishantiw commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +	// https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#bounce
why we changed this to single comment? I thought we are following TypeDoc way to mention LIP references?

2023-01-23 13:53 UTC, ishantiw commented on framework/src/modules/interoperability/constants.ts
> +// https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#empty-cross-chain-message
same here

2023-01-23 14:39 UTC, merged