Command `transaction:create` should not prompt user to re-enter passphrase
LiskHQ/lisk-sdk pull request #8073
Opened 2023-01-25 10:01 UTC by bobanm

### What was the problem?

This PR resolves #8072

### How was it solved?

`transaction:create` no longer invokes `getPassphraseFromPrompt()` with `shouldConfirm` argument.

### How was it tested?

All tests OK 👌🏻

2023-01-25 17:12 UTC, shuse2 requested changes

2023-01-25 17:12 UTC, shuse2 commented on commander/src/bootstrapping/commands/keys/encrypt.ts
> +		const password = flags.password ?? (await getPasswordFromPrompt('password'));
As discussed offline, when `encrypt` we should confirm the password

2023-01-25 17:12 UTC, shuse2 commented on commander/src/bootstrapping/commands/passphrase/encrypt.ts
> +		const passphrase = passphraseSource ?? (await getPassphraseFromPrompt('passphrase'));
same as above

2023-01-25 17:12 UTC, shuse2 commented on commander/src/commands/message/encrypt.ts
> +		const passphrase = passphraseSource ?? (await getPassphraseFromPrompt('passphrase'));
same as above

2023-01-26 13:26 UTC, mosmartin approved these changes
🚀

2023-01-26 15:26 UTC, shuse2 approved these changes

2023-01-26 16:55 UTC, merged