Fix transaction:create to create command without params
LiskHQ/lisk-sdk pull request #8089
Opened 2023-01-26 20:33 UTC by shuse2

### What was the problem?

This PR resolves #8088 

### How was it solved?

- Fix the check to expect undefined schema

### How was it tested?

- Added unit test
- Run `./bin/run transaction:create pos unlock` command

2023-01-26 22:11 UTC, has5aan approved these changes
🚀

2023-01-27 05:07 UTC, bobanm requested changes

2023-01-27 05:07 UTC, bobanm commented on commander/test/bootstrapping/commands/transaction/create.spec.ts
> +			describe(`transaction:create pos unlock 100000000 --params=${voteParams} --passphrase=${passphrase}`, () => {
Test description mentions that `--params` flag is being used, while it correctly invokes command without `--params` flag.

2023-01-27 08:45 UTC, bobanm approved these changes

2023-01-27 09:22 UTC, merged