Update getStakerResponseSchema
LiskHQ/lisk-sdk pull request #8228
Opened 2023-03-06 13:52 UTC by Incede

### What was the problem?

This PR resolves #8083 

### How was it solved?

Update as specified

### How was it tested?

N/A

2023-03-06 16:16 UTC, shuse2 requested changes

2023-03-06 16:16 UTC, shuse2 commented on framework/src/modules/pos/schemas.ts
>  		sentStakes: {
here also need to be changed to `stakes`

2023-03-07 10:55 UTC, has5aan approved these changes

2023-03-07 10:56 UTC, shuse2 approved these changes

2023-03-07 16:38 UTC, merged