Add a setHashOnionUsage endpoint
LiskHQ/lisk-sdk pull request #8249
Opened 2023-03-09 15:13 UTC by Incede

### What was the problem?

This PR resolves #8122 

### How was it solved?

Implement endpoint to set hash onion parameters

### How was it tested?

Added unit tests

2023-03-09 21:18 UTC, shuse2 requested changes

2023-03-09 21:18 UTC, shuse2 commented on framework/src/modules/random/endpoint.ts
> +		const { seed, count, distance, height } = ctx.params;
i think `seed` and `distance` can be set from the `setHashOnion` function, so they are not necessary. Also, `count` here is used in total # of hashes and # of hashes used

2023-03-10 11:51 UTC, shuse2 approved these changes

2023-03-10 12:21 UTC, mosmartin approved these changes
🚀

2023-03-10 13:23 UTC, merged