Fix genesis block missing validation
LiskHQ/lisk-sdk pull request #8441
Opened 2023-05-10 15:26 UTC by shuse2

### What was the problem?

This PR resolves #8439 

### How was it solved?

- Add missing validation for generator address and validators hash

### How was it tested?

- Add corresponding unit test

2023-05-11 09:55 UTC, AndreasKendziorra requested changes

2023-05-11 09:55 UTC, AndreasKendziorra commented on elements/lisk-chain/test/unit/block_header.spec.ts
> +			it('should throw error if generatorAddress is zero bytes', () => {
```suggestion
			it('should throw error if generatorAddress is not zero bytes', () => {
```

2023-05-12 06:49 UTC, AndreasKendziorra approved these changes

2023-05-12 07:36 UTC, has5aan approved these changes

2023-05-12 12:38 UTC, merged