Improve block processing tests
LiskHQ/lisk-sdk pull request #8444
Opened 2023-05-11 17:09 UTC by shuse2

### What was the problem?

This PR resolves #8135 

### How was it solved?

- Added missing unit tests

### How was it tested?

- All the missing tests the issue mentioned is added except the one replied in the comment of #8135

2023-05-12 12:03 UTC, AndreasKendziorra requested changes
There are still some points in #8135 that are in discussion.
Moreover, the following point from #8135 was not addressed:

> Some more precise tests regarding MAX_TRANSACTIONS_SIZE_BYTES than the [exiting one](https://github.com/LiskHQ/lisk-sdk/blob/42897f79e56bcf28a876899a91f73cb98c0a7932/elements/lisk-chain/test/unit/chain.spec.ts#L318) would be good. That means, one test where the size equals MAX_TRANSACTIONS_SIZE_BYTES and that passes. And one test where the size equals MAX_TRANSACTIONS_SIZE_BYTES+1 and that fails.

2023-05-15 08:27 UTC, Incede approved these changes

2023-05-15 08:27 UTC, Incede commented on elements/lisk-chain/src/block_assets.ts
> +					'Assets Assets are not sorted by the module property value in lexicographical order.',
```suggestion
					'Assets are not sorted by the module property value in lexicographical order.',
```

2023-05-15 09:11 UTC, AndreasKendziorra commented
I just saw that I falsely left my [question](https://github.com/LiskHQ/lisk-sdk/issues/8135#issuecomment-1547401667) regarding `MAX_TRANSACTIONS_SIZE_BYTES` in the issue instead of here. I would do the next review once this discussion is settled or addressed.

2023-05-15 09:45 UTC, shuse2 commented
@AndreasKendziorra I updated the chain test for the payload size test in https://github.com/LiskHQ/lisk-sdk/pull/8444/commits/621d94a595a5b01d2e98c7a49c8c729b32673fb7

2023-05-15 10:14 UTC, AndreasKendziorra approved these changes

2023-05-15 10:23 UTC, merged