Define genesis PoA store schema & relevant types
LiskHQ/lisk-sdk pull request #8501
Opened 2023-05-26 07:11 UTC by sitetester

### What was the problem?

This PR resolves #8500 

Schema & relevant types defined

2023-05-26 12:37 UTC, mitsuaki-u requested changes

2023-05-26 12:37 UTC, mitsuaki-u commented on framework/src/modules/poa/schemas.ts
> +								dataType: 'bytes',
you should use `minLength` and `maxLength` and set it to `NUM_BYTES_ADDRESS`

2023-05-30 09:41 UTC, mitsuaki-u approved these changes

2023-05-31 07:51 UTC, ishantiw reviewed
LGTM, left one comment

2023-05-31 07:51 UTC, ishantiw commented on framework/src/modules/poa/schemas.ts
> +export const genesisPoAStoreSchema = {
`$id` is missing

2023-06-01 14:40 UTC, merged