:bug: Fix node crash on multiple trasnactions
LiskHQ/lisk-sdk pull request #8632
Opened 2023-06-20 12:34 UTC by shuse2

### What was the problem?

This PR resolves #8610 

### How was it solved?

- Fix how transaction pool and generator communicates

### How was it tested?

TBD

2023-06-21 13:59 UTC, bobanm requested changes

2023-06-21 13:59 UTC, bobanm commented on elements/lisk-transaction-pool/src/transaction_pool.ts
> +				}
It seems to me that this loop and the very next one `for (const tx of allTransactions)` could be combined in one?

2023-06-21 15:38 UTC, ishantiw commented on elements/lisk-transaction-pool/src/transaction_pool.ts
> +			const veirfyResults = [];
also in other paces below
```suggestion
			const verifyResults = [];
```

2023-06-21 15:38 UTC, ishantiw commented on elements/lisk-transaction-pool/test/unit/transaction_pool.spec.ts
>  			const tempApplyTransactionsStub = jest.fn();
also in other places below
```suggestion
			const tempVerifyTransactionsStub = jest.fn();
```

2023-06-21 15:38 UTC, ishantiw commented on elements/lisk-transaction-pool/test/unit/transaction_pool.spec.ts
>  			const tempApplyTransactionsStub = jest.fn();
```suggestion
			const tempVerifyTransactionsStub = jest.fn();
```

2023-06-21 15:38 UTC, ishantiw commented on elements/lisk-transaction-pool/src/types.ts
>  }
I think we can simply do,
```
export enum TransactionStatus {
	INVALID = -1,
	UNPROCESSABLE,
	PROCESSABLE,
}
```

2023-06-22 11:05 UTC, bobanm approved these changes

2023-06-22 12:32 UTC, ishantiw approved these changes

2023-06-22 12:32 UTC, merged