Update token module with additional checks and LIP updates
LiskHQ/lisk-sdk pull request #8637
Opened 2023-06-22 14:07 UTC by Incede

### What was the problem?

This PR resolves #8580

### How was it solved?

Update token module as specified

### How was it tested?

Added unit tests

2023-06-22 16:14 UTC, mjerkov approved these changes
Looks good!

2023-06-23 01:42 UTC, shuse2 requested changes

2023-06-23 01:42 UTC, shuse2 commented on framework/test/unit/modules/token/init_genesis_state_fixture.ts
> +import { CHAIN_ID_LENGTH } from '../../../../src/modules/token/constants';
import should come under license

2023-06-23 03:02 UTC, shuse2 approved these changes

2023-06-23 03:02 UTC, merged