ccm certificate validation
LiskHQ/lisk-sdk pull request #8726
Opened 2023-07-12 00:11 UTC by Phanco

### What was the problem?

This PR resolves #8551

### How was it solved?

### How was it tested?

2023-07-19 12:25 UTC, mitsuaki-u requested changes

2023-08-03 12:10 UTC, mitsuaki-u approved these changes
Minor comment

2023-08-03 12:10 UTC, mitsuaki-u commented on framework/test/unit/modules/interoperability/utils.spec.ts
> +		it('should throw if certificate does not comply schema', () => {
```suggestion
		it('should throw if certificate does not comply with schema', () => {
```

2023-08-04 16:37 UTC, Phanco commented on framework/src/modules/interoperability/utils.ts
> +export const validateCertificate = (certificate: Certificate) => {
this function is consistent with `validateFormat`

2023-08-08 14:19 UTC, merged