Simplify code for getAllAccounts(...)
LiskHQ/lisk-sdk pull request #8749
Opened 2023-07-18 09:03 UTC by sitetester

### What was the problem?

This PR resolves #8549

### How was it solved?
Code simplified 

### How was it tested?
Tests are passing

2023-07-24 07:44 UTC, shuse2 requested changes

2023-07-24 07:44 UTC, shuse2 commented on framework/src/modules/interoperability/stores/chain_account.ts
> +		return Promise.all(chainAccounts.map(chainAccount => chainAccount.value));
I think `Promise.all` is not needed here?

2023-07-24 16:05 UTC, shuse2 approved these changes

2023-07-27 09:34 UTC, mitsuaki-u approved these changes

2023-07-27 12:56 UTC, merged