Update apply method per updated LIP changes
LiskHQ/lisk-sdk pull request #8769
Opened 2023-07-25 08:05 UTC by sitetester

### What was the problem?

This PR resolves #8733

### How was it solved?

Updates applied

### How was it tested?

& test cases updated

2023-08-01 07:54 UTC, shuse2 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +	): Promise<{ anyError: boolean }> {
if this just need to return boolean, it would be better to just return `false` when failed and true for success

2023-08-01 07:54 UTC, shuse2 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +	): Promise<{ anyError: boolean }> {
same for below

2023-08-01 08:52 UTC, shuse2 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +			result = false;
you can `return false`; here and return `true` at the end

2023-08-02 14:02 UTC, ricott1 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +		return true;
Shouldn't we return a Promise?

2023-08-02 14:02 UTC, ricott1 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +		return true;
same as above, should we return a Promise?

2023-08-02 14:04 UTC, ricott1 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +		const crossChainCommands = this.ccCommands.get(ccm.module);
I'm a bit confused by this interface, basically here we check if the module is supported?

2023-08-02 14:05 UTC, ricott1 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +		const crossChainCommand = crossChainCommands.find(com => com.name === ccm.crossChainCommand);
Wouldn't it be cleaner to merge this branch with the unsupported module one? It would avoid quite a bit of code repetition

2023-08-02 14:11 UTC, ricott1 requested changes
One bug and a couple minor points

2023-08-02 15:04 UTC, ricott1 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +		const crossChainCommand = crossChainCommands.find(com => com.name === ccm.crossChainCommand);
sorry by branch I meant code branch, i.e. the check at line 283

2023-08-02 15:05 UTC, ricott1 commented on framework/src/modules/interoperability/base_cross_chain_update_command.ts
> +		return true;
nice, I learned something :)

2023-08-08 07:13 UTC, ricott1 approved these changes

2023-08-08 10:25 UTC, merged