Update message recovery logic and refactor tests
LiskHQ/lisk-sdk pull request #8816
Opened 2023-08-07 11:12 UTC by mitsuaki-u

### What was the problem?

This PR resolves #8738 

### How was it solved?

- Added context store which keeps track of ccm processing
- Moved merkle tree verify logic to execute
- Refactored message recovery tests

### How was it tested?

Updated tests

2023-08-09 10:09 UTC, ricott1 approved these changes

2023-08-10 08:26 UTC, ishantiw requested changes

2023-08-10 08:26 UTC, ishantiw commented on framework/src/modules/interoperability/mainchain/commands/recover_message.ts
> +		const isVerified = regularMerkleTree.verifyDataBlock(
I think we also need to remove it from verify function after moving it here

2023-08-10 08:54 UTC, ishantiw requested changes

2023-08-10 08:54 UTC, ishantiw commented on framework/test/unit/modules/interoperability/mainchain/commands/recover_message.spec.ts
> +			const result = await command.verify(commandExecuteContext);
we need to call execute after we remove it from verify function. Also, add an assertion if  InvalidRMTVerification was called or not

2023-08-11 12:45 UTC, ishantiw requested changes

2023-08-15 08:40 UTC, ishantiw approved these changes

2023-08-15 12:21 UTC, merged