Adds Config, Index and Votes stores for Governance module
LiskHQ/lisk-sdk pull request #8925
Opened 2023-09-01 13:52 UTC by has5aan

### What was the problem?

This PR resolves #8864, #8865 and #8866.

### How was it solved?

Implemented/Updated `ConfigStore`, `IndexStore` and `VotesStore`.

2023-09-03 23:51 UTC, bobanm commented on framework/src/modules/governance/stores/index.ts
> +}
Following @shuse2 [suggestion](https://github.com/LiskHQ/lisk-sdk/pull/8888#discussion_r1302576852), we have renamed `IndexStore` into `ProposalIndexStore` and you can find the foundation in `proposal_index.ts` file.

2023-09-03 23:57 UTC, bobanm commented on framework/src/modules/governance/stores/config.ts
> +			type: 'bytes',
All encode/decode schemas should use `dataType` instead of `type`.

2023-09-03 23:59 UTC, bobanm requested changes
Additional comment: When 1 PR is supposed to resolve multiple issues, I think it is required to use keyword `resolves` multiple times, in front of every issue ID, e.g:

> resolves #xxxx, resolves #yyyy, resolves, #zzzz

2023-09-11 21:53 UTC, shuse2 approved these changes

2023-09-11 21:53 UTC, merged