Unit test review - Interoperability genesis state initialization/finalization
LiskHQ/lisk-sdk pull request #8980
Opened 2023-09-14 07:15 UTC by sitetester

### What was the problem?

This PR resolves #8378

### How was it solved?
Went through source code & corresponding tests added/updated. Also mainchain:_verifyTerminatedStateAccounts(...) is updated.

### How was it tested?

Added/updated tests are passing

2023-09-15 13:35 UTC, ishantiw requested changes
- We can be consistent with other test suites in the SDK following the pattern of, describe blocks for each method and if it needs further describe it with words, for example, the below desc block doesn't really speak much,
https://github.com/LiskHQ/lisk-sdk/blob/17d63fb6fbe509b38288fafe681456d122d8b0ce/framework/test/unit/modules/interoperability/base_interoperability_module.spec.ts#L352

2023-09-15 13:35 UTC, ishantiw commented on framework/test/unit/modules/interoperability/mainchain/module.spec.ts
> +	describe('verifyTerminatedStateAccounts', () => {
desc should match the name of the method
```suggestion
	describe('_verifyTerminatedStateAccounts', () => {
```

2023-09-15 13:35 UTC, ishantiw commented on framework/test/unit/modules/interoperability/mainchain/module.spec.ts
> +			// doesn't matter what it throw it this stage
Not sure what this comment means, maybe elaborate or remove it if its not important, also the statement is not correct
`// doesn't matter what it throw at this stage`

2023-09-19 08:52 UTC, ishantiw requested changes
I think this comment is not resolved yet
https://github.com/LiskHQ/lisk-sdk/pull/8980#pullrequestreview-1628878236

2023-09-20 10:38 UTC, gkoumout requested changes
Good job! Left some small comments.

2023-09-20 10:38 UTC, gkoumout commented on framework/test/unit/modules/interoperability/mainchain/module.spec.ts
> +		it('should not throw error if length of terminatedStateAccounts is zero', async () => {
I am not sure what is the intention for this test. In fact, if length of terminatedStateAccounts is zero while there exist some chain in chainData with status `TERMINATED`, then it should throw an error..

2023-09-20 10:38 UTC, gkoumout commented on framework/test/unit/modules/interoperability/mainchain/module.spec.ts
> +		it('should not throw error if length of terminatedStateAccounts is zero', async () => {
So my guess is that this should be split into two:

 - if length of terminatedStateAccounts is 0 and there exists a terminated chain, it should throw an error
 - if length of terminatedStateAccounts is 0 and there does not exist a terminated chain, it should NOT throw an error.

2023-09-20 10:38 UTC, gkoumout commented on framework/src/modules/interoperability/mainchain/module.ts
> +		this._verifyChainInfos(ctx, chainInfos, ownChainNonce);
Here I assume it's just a re-structuring change, by moving the nonce-length checks inside the `verifyChainInfos` function and there is no change in the logic. Is that right?

2023-09-22 16:22 UTC, gkoumout reviewed
only one minor comment remaining

2023-09-22 16:22 UTC, gkoumout commented on framework/test/unit/modules/interoperability/base_interoperability_module.spec.ts
> +				terminatedStateAccounts.length * 2,
But those are unit tests for `_verifyTerminatedStateAccountsCommon`, right?

2023-09-27 07:58 UTC, gkoumout approved these changes

2023-09-27 07:58 UTC, gkoumout commented on framework/test/unit/modules/interoperability/base_interoperability_module.spec.ts
> +			expect(interopModPrototype['_verifyChainID']).toHaveBeenCalledTimes(
I guess it's ok now. @ishantiw please have a look as well since I am not fully comfortable with verifying the correctness of unit tests.

2023-10-12 14:24 UTC, ishantiw requested changes
Please apply this commit  https://github.com/LiskHQ/lisk-sdk/pull/9079/commits/97e6fee4abb8d1fab4feb907cad0579af98ba4d5 as it contains a minor bug

2023-10-13 10:08 UTC, merged