Simplify getBytes and getSigningBytes
LiskHQ/lisk-sdk pull request #9062
Opened 2023-10-04 04:20 UTC by bobanm

### What was the problem?

This PR resolves #9061

### How was it solved?

- Extracted common functionality to `encodeParams()` function
- Reverted the conditional for checking if params are valid

### How was it tested?

All existing tests have passed 👌🏻

2023-10-04 06:24 UTC, shuse2 requested changes

2023-10-04 06:24 UTC, shuse2 commented on elements/lisk-transactions/src/sign.ts
> +	}
Actually this code is outdated and it will never be executed

2023-10-04 06:24 UTC, shuse2 commented on elements/lisk-transactions/src/sign.ts
> +const encodeParams = (transaction: Record<string, unknown>, paramsSchema?: object): Buffer => {
you can use `emptySchema` when undefined for paramsSchema now

2023-10-25 11:40 UTC, has5aan approved these changes

2023-10-30 08:45 UTC, shuse2 approved these changes

2023-11-01 17:08 UTC, merged