Fix validator unshuffling
LiskHQ/lisk-sdk pull request #9088
Opened 2023-10-12 14:01 UTC by bobanm

### What was the problem?

This PR resolves #9040 and resolves #9075

### How was it solved?

- Fixed the bug in the engine where the original validator list array was sorted and then saved in sorted order to BFT Params Store
- Added config option [default to 0] to prevent validator shuffling before the configured block height, to ensure that the the new version can sync
- BONUS: Cleaned up and simplified BFT Method unit tests 😎 

### How was it tested?

- When running the app, validator's consecutive missed blocks now show correct value
- When running the app, the validators are shuffled after each round
- All tests are passing 👌🏻

2023-10-12 15:04 UTC, ishantiw commented on framework/src/engine/bft/method.ts
> +		const validatorsWithBFTWeight = validators
probably we can add a comment on top of this to be careful in the future `Prepare a separate sorted list of validators for computing validatorsHash without modifying the existing validators array`

2023-10-12 15:05 UTC, shuse2 requested changes

2023-10-12 15:05 UTC, shuse2 commented on framework/test/unit/engine/bft/method.spec.ts
> +				const shuffledValidators = [...validators];
ah the test input was also sorted 😢

2023-10-12 15:05 UTC, shuse2 commented on framework/test/unit/engine/bft/method.spec.ts
> +				expect(bftParams.validators[2].address).toEqual(shuffledValidators[2].address);
also it's good to check the exception case as well

2023-10-12 21:35 UTC, shuse2 approved these changes
🚀

2023-10-13 08:21 UTC, ishantiw approved these changes
👏

2023-10-13 08:40 UTC, merged